// Generated from Douyu live chat emoji panel (ChatEmotion / EmotionList).
// Source: shark2.douyucdn.cn（斗鱼全站统一表情，8 个表情库共 265 个）。
library;

import 'package:simple_live_core/simple_live_core.dart';
import 'package:simple_live_core/src/danmaku/common_emoji_assets.dart';

const Map<String, String> douyuEmojiAssets = {
  '[666]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/liuliuliu_67db810.png',
  '[6666]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/6666_e3dd0e9.png',
  '[财神]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/caishen_8daad7a.png',
  '[狗骨头]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/gougutou_12b4a87.png',
  '[牛啤]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/niupi_c6b2a00.png',
  '[庆祝]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qingzhu_4e9364d.png',
  '[RUA]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/rua_a2008d1.png',
  '[投币]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/toubi_bfc050c.png',
  '[土块]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tukuai_40eed66.png',
  '[VIP]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/vip_a27cf8f.png',
  '[指责]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhize_0c5c59c.png',
  '[打扰了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daraole_a5759cc.png',
  '[毒奶]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dunai_9d43a6b.png',
  '[反向烟]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fanxiangyan_598ea74.png',
  '[富贵饼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fuguibing_61f3914.png',
  '[搞起]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/gaoqi_1e976db.png',
  '[好样的]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/haoyangde_2278fd9.png',
  '[金牌]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jinpai_a203913.png',
  '[口香糖]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kouxiangtang_2a39913.png',
  '[上课]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shangke_2c5b877.png',
  '[旭宝宝]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xubaobao_3dc3a79.png',
  '[真香]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhenxiang_f59448a.png',
  '[爱你]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/aini_a5ddae2.png',
  '[挨揍]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/aizou_233d6d5.png',
  '[搬砖]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/banzhuan_d7f5046.png',
  '[宝宝]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baobao_f96ccbf.png',
  '[被揍了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/beizoule_d293f04.png',
  '[财迷]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/caimi_470d018.png',
  '[吃瓜]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chigua_3c5cf0b.png',
  '[打call]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dacall_d2c0c65.png',
  '[大哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daku_33bef26.png',
  '[大马猴]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/damahou_dea6856.png',
  '[大怒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/danu_8e1ef86.png',
  '[点赞]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dianzan_dd6d5cf.png',
  '[愤怒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fennu_347668b.png',
  '[鬼脸]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/guilian_8ff7c06.png',
  '[好色]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/haose_7c06b19.png',
  '[加油]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiayou_bd595a6.png',
  '[惊吓]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jingxia_e562d67.png',
  '[开心]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kaixin_48bc14e.png',
  '[哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ku_e8925ea.png',
  '[困]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kun_af9abc8.png',
  '[OK]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/OK_1079d5a.png',
  '[潜水]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qianshui_54ef2e5.png',
  '[欠揍]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qianzou_0dac040.png',
  '[骚猪]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/saozhu_55aa768.png',
  '[社会人]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shehuiren_781f5c8.png',
  '[他来了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/talaile_e847a7d.png',
  '[偷笑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/touxiao_10bf7c0.png',
  '[心碎]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xinsui_9f6eee0.png',
  '[羞涩]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiuse_c3a7b03.png',
  '[疑惑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yihuo_ee678d3.png',
  '[有意思]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/youyisi_302d755.png',
  '[原谅]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yuanliang_e802e0a.png',
  '[再见]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zaijian_704c0ab.png',
  '[炸鱼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhayu_864b2ad.png',
  '[真的么]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhendeme_d5dc347.png',
  '[住口]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhukou_cb74ab5.png',
  '[大叫]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dajiao_d8e4f3d.png',
  '[就这]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiuzhe_ca93c68.png',
  '[口罩]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kouzhao_18771f5.png',
  '[喷子]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/penzi_f9900d3.png',
  '[招财猫]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhaocaimao_e52111d.png',
  '[白妹]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baimei_c02a7d8.png',
  '[半遮面]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/banzhemian_63ad982.png',
  '[憨憨]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/hanhan_9bce763.png',
  '[开车]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kaiche_5da53a8.png',
  '[奈斯]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/naisi_9c8230e.png',
  '[嘻嘻]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xixi_d9f42a9.png',
  '[暴躁]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baozao_9cd8ecf.png',
  '[吃惊]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chijing_ff6ad76.png',
  '[瞅瞅]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chouchou_70e06c4.png',
  '[发狂]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fakuang_714ca05.png',
  '[跟我来]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/genwolai_0993438.png',
  '[呱呱]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/guagua_b735435.png',
  '[鼓掌]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/guzhang_7307034.png',
  '[哈喽]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/halou_710cca7.png',
  '[好困]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/haokun_bcbfee4.png',
  '[哼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/heng_c6b08c9.png',
  '[猴子]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/houzi_0c868ce.png',
  '[绝望]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/juewang_f687054.png',
  '[乐呵]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/lehe_996dbeb.png',
  '[喵喵]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/miaomiao_ec280cf.png',
  '[内伤]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/neishang_0e0ed95.png',
  '[凝视]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ningshi_8d0bed4.png',
  '[期待]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qidai_4f4d65d.png',
  '[伤感]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shanggan_d6e4711.png',
  '[伤心]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shangxin_51a921e.png',
  '[生气]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shengqi_72c1381.png',
  '[思考]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/sikao_97e9d04.png',
  '[six]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/six_02f6b81.png',
  '[天呐]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tianna_ee42268.png',
  '[调戏]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tiaoxi_957638f.png',
  '[哇]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wa_281d84c.png',
  '[我去]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/woqu_7e1f88a.png',
  '[咬]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yao_376d56d.png',
  '[有毒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/youdu_aa0e7b1.png',
  '[赞一个]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zanyige_088bee5.png',
  '[阵亡]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhenwang_7734ef7.png',
  '[顽皮]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wanpi_a1ec707.png',
  '[恐惧]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kongju_43afb2e.png',
  '[小恶魔]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiaoemo_84148c3.png',
  '[被揍]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/beizou_6a6fab7.png',
  '[闭嘴]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bizui_6fb32e0.png',
  '[不会吧]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/buhuiba_cf060a7.png',
  '[大笑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daxiao_1d13a5a.png',
  '[尬笑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/gaxiao_b707a89.png',
  '[嘿嘿嘿]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/heiheihei_ee03007.png',
  '[惶恐]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/huangkong_094e988.png',
  '[惊讶]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jingya_6a1815f.png',
  '[酷酷的]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kukude_8fe2d36.png',
  '[篮球]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/lanqiu_feabd73.png',
  '[冒金光]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/maojinguang_758c00f.png',
  '[萌化了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/menghuale_f3ffd67.png',
  '[怒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/nu_e90986f.png',
  '[呕吐]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/outu_085a700.png',
  '[拼了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/pinle_6594843.png',
  '[亲亲]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qinqin_a93912e.png',
  '[傻了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shale_2320b24.png',
  '[升天]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shengtian_dfc53b9.png',
  '[石化]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shihua_15ab59c.png',
  '[受伤]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shoushang_888e795.png',
  '[睡觉]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shuijiao_ef1127d.png',
  '[舔屏]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tianping_fa68b14.png',
  '[痛哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tongku_aa35a58.png',
  '[偷偷笑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/toutouxiao_370c652.png',
  '[我方了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wofangle_3dccc68.png',
  '[无奈]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wunai_c09b3f4.png',
  '[熊猫眼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiongmaoyan_638cfe0.png',
  '[压力大]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yalida_e9dd4ad.png',
  '[晕了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yunle_5e61342.png',
  '[足球]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zuqiu_4352501.png',
  '[憋说了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bieshuole_857bd72.png',
  '[沉江]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chenjiang_476b14a.png',
  '[锤子]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chuizi_8e9f00b.png',
  '[逮捕]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daibu_79a7c66.png',
  '[刀刀刀]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daodaodao_91401a2.png',
  '[大气]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daqi_23d6549.png',
  '[GDX]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/gdx_3a4760d.png',
  '[鸽了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/gele_485007a.png',
  '[隔离]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/geli_bf005f6.png',
  '[舒服了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shufule_bfdd21a.png',
  '[嫌弃]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xianqi_a501bcc.png',
  '[爷]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ye_b5315ce.png',
  '[skr]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/skr_0058f9c.png',
  '[草帽]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/caomao_b112004.png',
  '[大鹌鹑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daanchun_edc3df6.png',
  '[护目镜]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/humujing_3d21d2a.png',
  '[教科书]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiaokeshu_aaae255.png',
  '[辣眼睛]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/layanjing_4e42ecc.png',
  '[圣诞帽]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shengdanmao_8baa3ba.png',
  '[抬杠]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/taigang_cdb7c94.png',
  '[拜托]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baituo_c245f1b.png',
  '[棒棒哒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bangbangda_8c71346.png',
  '[冰冻]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bingdong_f9a60fc.png',
  '[吃瓜瓜]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chiguagua_e899cfc.png',
  '[冲鸭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chongya_ecd9639.png',
  '[呲牙]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ciya_cf0bfa7.png',
  '[电击]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dianji_3a49e4d.png',
  '[DIE]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/DIE_25ad940.png',
  '[肥宅]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/feizhai_0b4a9da.png',
  '[尴尬]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ganga_81fe320.png',
  '[害怕]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/haipa_06a4846.png',
  '[僵尸]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiangshi_1b1ddae.png',
  '[紧张]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jinzhang_34a271e.png',
  '[纠结]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiujie_1c190f2.png',
  '[抠鼻孔]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/koubikong_f657eed.png',
  '[略略略]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/lueluelue_3ed3916.png',
  '[绿了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/lvle_547dfaa.png',
  '[没问题]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/meiwenti_10e13f0.png',
  '[奶茶]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/naicha_a9be78d.png',
  '[柠檬精]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ningmengjing_3d86a78.png',
  '[喷火]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/penhuo_fad6380.png',
  '[欠扁]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qianbian_2e59b59.png',
  '[讨厌]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/taoyan_c4825d5.png',
  '[哇哦]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wao_12d9b15.png',
  '[哇哇哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wawaku_87e514d.png',
  '[我可]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/woke_f31754a.png',
  '[无聊]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wuliao_dc3ac4f.png',
  '[要抱抱]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yaobaobao_8383cf3.png',
  '[注视你]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhushini_cbc6070.png',
  '[囧]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiong_854e3d1.png',
  '[没电了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/meidianle_d8c4dc7.png',
  '[摸鱼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/moyu_bc4f139.png',
  '[死机]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/siji_35a9397.png',
  '[太南了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tainanle_7f5251a.png',
  '[爆米花]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baomihua_d1c2bc8.png',
  '[爆头]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/baotou_2cf8f10.png',
  '[不高兴]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bugaoxing_6a76736.png',
  '[call]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/call_535637d.png',
  '[打劫]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dajie_a946737.png',
  '[发火]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fahuo_d6f96ec.png',
  '[发怒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fanu_ea090f6.png',
  '[扶墙]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fuqiang_45de94a.png',
  '[干杯]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ganbei_b119b6d.png',
  '[GG]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/GG_b9880f8.png',
  '[害羞]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/haixiu_1473554.png',
  '[喝酒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/hejiu_8f2ab50.png',
  '[花屏]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/huaping_39be9e8.png',
  '[冷]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/leng_92f61c7.png',
  '[面膜]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/mianmo_7806b5a.png',
  '[潜泳]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qianyong_44f5b72.png',
  '[请表演]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qingbiaoyan_7873e95.png',
  '[啥情况]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shaqingkuang_3e3171f.png',
  '[示爱]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shiai_4af5b65.png',
  '[晚安]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wanan_5a7e103.png',
  '[微笑]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/weixiao_a6fa8a2.png',
  '[我最棒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wozuibang_c65c7f0.png',
  '[无语]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wuyu_0049c2e.png',
  '[吓一跳]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiayitiao_0a7f91e.png',
  '[嘘]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xu_f3ada46.png',
  '[耶]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ye_e884efb.png',
  '[幽灵]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/youling_788a38f.png',
  '[优秀]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/youxiu_f3cf114.png',
  '[张嘴]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhangzui_74acd7b.png',
  '[震惊]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/zhenjing_00ca081.png',
  '[奥利给]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/aoligei_31c928c.png',
  '[彩虹屁]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/caihongpi_9f9aacd.png',
  '[裂开]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/liekai_0586d68.png',
  '[膨胀]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/pengzhang_44b82a0.png',
  '[天降正义]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tianjiangzhengyi_488cc82.png',
  '[啵一个]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/boyige_8c92e3c.png',
  '[沉默]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chenmo_a3e540a.png',
  '[C位]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/cwei_f680163.png',
  '[大喊]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dahan_2f1197c.png',
  '[大吼]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dahou_ae463bf.png',
  '[得意]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/deyi_13e47f1.png',
  '[顶呱呱]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/dingguagua_be7be27.png',
  '[犯困]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/fankun_899c2ad.png',
  '[僵硬]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiangying_fffcdd6.png',
  '[惊恐]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jingkong_f13e2ef.png',
  '[可怜]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kelian_94d7798.png',
  '[雷击]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/leiji_9caeb0a.png',
  '[卖萌]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/maimeng_beabdab.png',
  '[没话说]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/meihuashuo_185fef8.png',
  '[藐视]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/miaoshi_7a17616.png',
  '[你瞅啥]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/nichousha_b321a84.png',
  '[扭捏]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/niunie_07f79c0.png',
  '[呕]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/ou_7daf6f4.png',
  '[喷血]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/penxue_8145671.png',
  '[气氛]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qifen_50bbb00.png',
  '[气哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qiku_8fe158e.png',
  '[闪亮]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shanliang_e13689c.png',
  '[失望]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shiwang_91d86a5.png',
  '[太蓝了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/tailanle_d6b0c90.png',
  '[委屈]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/weiqu_46422f4.png',
  '[我来了]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/wolaile_09f861d.png',
  '[硬化]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yinghua_13b580a.png',
  '[疑问]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yiwen_515a3d6.png',
  '[晕倒]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yundao_5409f2e.png',
  '[晕眩]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/yunxuan_74d77bd.png',
  '[比心]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/bixin_3d646bc.png',
  '[什么]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shenme_2850187.png',
  '[冲冲冲]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/chongchongchong_adaebe4.png',
  '[谢谢啦]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiexiela_f2ceb2f.png',
  '[胜利]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/shengli_2e7d119.png',
  '[打扰啦]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/daraola_390c6bb.png',
  '[哭哭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/kuku_a53b578.png',
  '[MVP]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/mvp_c4f594b.png',
  '[加油啦]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/jiayoula_fcd9cd4.png',
  '[别毒奶]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/biedunai_f7f0d3b.png',
  '[给力嗷]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/geiliao_4b7e33b.png',
  '[给爷冲]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/geiyechong_06dfdd3.png',
  '[起立]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/qili_6f7420a.png',
  '[下饭]': 'https://shark2.douyucdn.cn/front-publish/live-next-player-aside-master/assets/images/xiafan_9054fd0.png',
};

final RegExp _douyuEmojiTokenPattern = RegExp(r'\[[^\[\]]{1,16}\]');

/// 斗鱼弹幕表情提取：优先斗鱼原版映射，未命中回退通用 Twemoji。
List<LiveMessageSpan> buildDouyuEmojiSpans(String content) {
  final spans = <LiveMessageSpan>[];
  var start = 0;
  for (final match in _douyuEmojiTokenPattern.allMatches(content)) {
    if (match.start > start) {
      spans.add(LiveMessageSpan.text(content.substring(start, match.start)));
    }
    final url = douyuEmojiAssets[match.group(0)] ??
        commonEmojiAssets[match.group(0)];
    if (url != null) {
      spans.add(LiveMessageSpan.image(url));
    } else {
      spans.add(LiveMessageSpan.text(match.group(0)!));
    }
    start = match.end;
  }
  if (start < content.length) {
    spans.add(LiveMessageSpan.text(content.substring(start)));
  }
  return spans;
}
