// Generated. Do not edit by hand.
// Douyin Android client: 40.0.0
// Source: Douyin Android small_emoji_res/emoji_android/info.json
// Generated at: 2026-08-12T16:30:00+08:00
library;

const String douyinMobileEmojiClientVersion = "40.0.0";
const String douyinMobileEmojiSource =
    "Douyin Android small_emoji_res/emoji_android/info.json";
const String douyinMobileEmojiGeneratedAt = "2026-08-12T16:30:00+08:00";
const int douyinMobileEmojiAssetCount = 455;
const int douyinMobileEmojiFileCount = 433;

const Map<String, String> douyinMobileEmojiAssets = {
  "[\u9cb8\u9c7c\u70b9\u8d5e]":
      "asset://assets/images/douyin_emoji/jingyudianzan.png",
  "[\u9cb8\u9c7c\u7231\u6155]":
      "asset://assets/images/douyin_emoji/jingyuaimu.png",
  "[\u9cb8\u9c7c\u505c\u673a]":
      "asset://assets/images/douyin_emoji/jingyutingji.png",
  "[\u9cb8\u9c7c\u5472\u7259]":
      "asset://assets/images/douyin_emoji/jingyuciya.png",
  "[\u9cb8\u9c7c\u5c2c\u7b11]":
      "asset://assets/images/douyin_emoji/jingyugaxiao.png",
  "[\u9cb8\u9c7c\u6d41\u6cea]":
      "asset://assets/images/douyin_emoji/jingyuliulei.png",
  "[\u9cb8\u9c7c\u6342\u8138]":
      "asset://assets/images/douyin_emoji/jingyuwulian.png",
  "[\u8fc7\u5e74\u725b]": "asset://assets/images/douyin_emoji/guonianniu.png",
  "[\u6234\u53e3\u7f69]": "asset://assets/images/douyin_emoji/daikouzhao.png",
  "[\u52e4\u6d17\u624b]": "asset://assets/images/douyin_emoji/qinxishou.png",
  "[\u4e0d\u4fe1\u8c23\u8a00]":
      "asset://assets/images/douyin_emoji/buxinyaoyan.png",
  "[\u5fae\u7b11]": "asset://assets/images/douyin_emoji/weixiao.png",
  "[\u8272]": "asset://assets/images/douyin_emoji/aimu.png",
  "[\u7231\u6155]": "asset://assets/images/douyin_emoji/aimu.png",
  "[\u53d1\u5446]": "asset://assets/images/douyin_emoji/liangdai.png",
  "[\u60ca\u5446]": "asset://assets/images/douyin_emoji/liangdai.png",
  "[\u9177\u62fd]": "asset://assets/images/douyin_emoji/kuye.png",
  "[\u62a0\u9f3b]": "asset://assets/images/douyin_emoji/koubi.png",
  "[\u6d41\u6cea]": "asset://assets/images/douyin_emoji/liulei.png",
  "[\u6342\u8138]": "asset://assets/images/douyin_emoji/wulian.png",
  "[\u53d1\u6012]": "asset://assets/images/douyin_emoji/fanu.png",
  "[\u5472\u7259]": "asset://assets/images/douyin_emoji/ziya.png",
  "[\u5c2c\u7b11]": "asset://assets/images/douyin_emoji/gaxiao.png",
  "[\u7761]": "asset://assets/images/douyin_emoji/hanshui.png",
  "[\u9f3e\u7761]": "asset://assets/images/douyin_emoji/hanshui.png",
  "[\u5bb3\u7f9e]": "asset://assets/images/douyin_emoji/haixiu.png",
  "[\u8c03\u76ae]": "asset://assets/images/douyin_emoji/keai.png",
  "[\u53ef\u7231]": "asset://assets/images/douyin_emoji/keai.png",
  "[\u8214\u5c4f]": "asset://assets/images/douyin_emoji/tianping.png",
  "[\u770b]": "asset://assets/images/douyin_emoji/kan.png",
  "[\u7231\u5fc3]": "asset://assets/images/douyin_emoji/xin.png",
  "[\u6bd4\u5fc3]": "asset://assets/images/douyin_emoji/bixin.png",
  "[\u8d5e]": "asset://assets/images/douyin_emoji/zan.png",
  "[\u9f13\u638c]": "asset://assets/images/douyin_emoji/guzhang.png",
  "[\u611f\u8c22]": "asset://assets/images/douyin_emoji/qidao.png",
  "[\u7948\u7977]": "asset://assets/images/douyin_emoji/qidao.png",
  "[\u62b1\u62b1\u4f60]": "asset://assets/images/douyin_emoji/baobaoni.png",
  "[\u73ab\u7470]": "asset://assets/images/douyin_emoji/meigui.png",
  "[\u5c34\u5c2c\u6d41\u6c57]":
      "asset://assets/images/douyin_emoji/gangaliuhan.png",
  "[\u6233\u624b\u624b]": "asset://assets/images/douyin_emoji/chuoshoushou.png",
  "[\u661f\u661f\u773c]": "asset://assets/images/douyin_emoji/xingxingyan.png",
  "[\u6740\u9a6c\u7279]": "asset://assets/images/douyin_emoji/shamate.png",
  "[\u9ec4\u8138\u5e72\u676f]":
      "asset://assets/images/douyin_emoji/huanglianganbei.png",
  "[\u62b1\u7d27\u81ea\u5df1]":
      "asset://assets/images/douyin_emoji/baojinziji.png",
  "[\u62dc\u62dc]": "asset://assets/images/douyin_emoji/baibai.png",
  "[\u70ed\u5316\u4e86]": "asset://assets/images/douyin_emoji/rehuale.png",
  "[\u9ec4\u8138\u7948\u7977]":
      "asset://assets/images/douyin_emoji/huanglianqidao.png",
  "[\u61f5]": "asset://assets/images/douyin_emoji/meng.png",
  "[\u4e3e\u624b]": "asset://assets/images/douyin_emoji/jushou.png",
  "[\u52a0\u529f\u5fb7]": "asset://assets/images/douyin_emoji/jiagongde.png",
  "[\u644a\u624b]": "asset://assets/images/douyin_emoji/tanshou.png",
  "[\u65e0\u8bed\u6d41\u6c57]":
      "asset://assets/images/douyin_emoji/wuyuliuhan.png",
  "[\u7eed\u706b\u82b1\u5427]":
      "asset://assets/images/douyin_emoji/xuhuohuaba.png",
  "[\u70b9\u706b]": "asset://assets/images/douyin_emoji/dianhuo.png",
  "[\u54ed\u54ed]": "asset://assets/images/douyin_emoji/kuku.png",
  "[\u9012\u82b1]": "asset://assets/images/douyin_emoji/dihua.png",
  "[\u70b9\u5934\u54c8\u8170]":
      "asset://assets/images/douyin_emoji/diantouhayao.png",
  "[\u5410\u820c\u5c0f\u72d7]":
      "asset://assets/images/douyin_emoji/tushexiaogou.png",
  "[\u9001\u82b1]": "asset://assets/images/douyin_emoji/songhua.png",
  "[\u7231\u5fc3\u624b]": "asset://assets/images/douyin_emoji/aixinshou.png",
  "[\u8d34\u8d34]": "asset://assets/images/douyin_emoji/tietie.png",
  "[\u7075\u673a\u4e00\u52a8]":
      "asset://assets/images/douyin_emoji/lingguangyishan.png",
  "[\u7075\u5149\u4e00\u95ea]":
      "asset://assets/images/douyin_emoji/lingguangyishan.png",
  "[\u8036]": "asset://assets/images/douyin_emoji/ye.png",
  "[\u6253\u8138]": "asset://assets/images/douyin_emoji/dalian.png",
  "[\u5927\u7b11]": "asset://assets/images/douyin_emoji/daxiao.png",
  "[\u673a\u667a]": "asset://assets/images/douyin_emoji/jizhi.png",
  "[\u9001\u5fc3]": "asset://assets/images/douyin_emoji/songxin.png",
  "[666]": "asset://assets/images/douyin_emoji/666.png",
  "[\u95ed\u5634]": "asset://assets/images/douyin_emoji/bizui.png",
  "[\u6765\u770b\u6211]": "asset://assets/images/douyin_emoji/laikanwo.png",
  "[\u4e00\u8d77\u52a0\u6cb9]":
      "asset://assets/images/douyin_emoji/yiqijiayou.png",
  "[\u54c8\u6b20]": "asset://assets/images/douyin_emoji/haqian.png",
  "[\u9707\u60ca]": "asset://assets/images/douyin_emoji/zhenliang.png",
  "[\u6655]": "asset://assets/images/douyin_emoji/yun.png",
  "[\u8870]": "asset://assets/images/douyin_emoji/shuai.png",
  "[\u56f0]": "asset://assets/images/douyin_emoji/kun.png",
  "[\u7591\u95ee]": "asset://assets/images/douyin_emoji/what.png",
  "[what]": "asset://assets/images/douyin_emoji/what.png",
  "[\u6ce3\u4e0d\u6210\u58f0]":
      "asset://assets/images/douyin_emoji/qibuchengsheng.png",
  "[\u5c0f\u9f13\u638c]": "asset://assets/images/douyin_emoji/xiaoguzhang.png",
  "[\u5927\u91d1\u7259]": "asset://assets/images/douyin_emoji/dajinya.png",
  "[\u5077\u7b11]": "asset://assets/images/douyin_emoji/touxiao.png",
  "[\u77f3\u5316]": "asset://assets/images/douyin_emoji/shihua.png",
  "[\u601d\u8003]": "asset://assets/images/douyin_emoji/sikao.png",
  "[\u5410\u8840]": "asset://assets/images/douyin_emoji/tuxie.png",
  "[\u53ef\u601c]": "asset://assets/images/douyin_emoji/kelian.png",
  "[\u5618]": "asset://assets/images/douyin_emoji/xu.png",
  "[\u6487\u5634]": "asset://assets/images/douyin_emoji/piezui.png",
  "[\u5c34\u5c2c]": "asset://assets/images/douyin_emoji/heixian.png",
  "[\u9ed1\u7ebf]": "asset://assets/images/douyin_emoji/heixian.png",
  "[\u7b11\u54ed]": "asset://assets/images/douyin_emoji/xiaoku.png",
  "[\u751f\u75c5]": "asset://assets/images/douyin_emoji/wumai.png",
  "[\u96fe\u973e]": "asset://assets/images/douyin_emoji/wumai.png",
  "[\u5978\u7b11]": "asset://assets/images/douyin_emoji/jianxiao.png",
  "[\u5f97\u610f]": "asset://assets/images/douyin_emoji/deyi.png",
  "[\u61a8\u7b11]": "asset://assets/images/douyin_emoji/hanxiao.png",
  "[\u574f\u7b11]": "asset://assets/images/douyin_emoji/huaixiao.png",
  "[\u6293\u72c2]": "asset://assets/images/douyin_emoji/zhuakuang.png",
  "[\u6cea\u5954]": "asset://assets/images/douyin_emoji/leiben.png",
  "[\u94b1]": "asset://assets/images/douyin_emoji/qian.png",
  "[\u4eb2\u4eb2]": "asset://assets/images/douyin_emoji/wen.png",
  "[\u543b]": "asset://assets/images/douyin_emoji/wen.png",
  "[\u6050\u60e7]": "asset://assets/images/douyin_emoji/kongju.png",
  "[\u6109\u5feb]": "asset://assets/images/douyin_emoji/xiao.png",
  "[\u7b11]": "asset://assets/images/douyin_emoji/xiao.png",
  "[\u5feb\u54ed\u4e86]": "asset://assets/images/douyin_emoji/kuaikule.png",
  "[\u7ffb\u767d\u773c]": "asset://assets/images/douyin_emoji/fanbaiyan.png",
  "[\u50b2\u6162]": "asset://assets/images/douyin_emoji/fanbaiyan.png",
  "[\u4e92\u7c89]": "asset://assets/images/douyin_emoji/hufen.png",
  "[\u6211\u60f3\u9759\u9759]":
      "asset://assets/images/douyin_emoji/woxiangjingjing.png",
  "[\u59d4\u5c48]": "asset://assets/images/douyin_emoji/weiqu.png",
  "[\u9119\u89c6]": "asset://assets/images/douyin_emoji/bishi.png",
  "[\u98de\u543b]": "asset://assets/images/douyin_emoji/feiwen.png",
  "[\u518d\u89c1]": "asset://assets/images/douyin_emoji/zaijian.png",
  "[\u7d2b\u8587\u522b\u8d70]":
      "asset://assets/images/douyin_emoji/ziweibiezou.png",
  "[\u542c\u6b4c]": "asset://assets/images/douyin_emoji/tingge.png",
  "[\u62e5\u62b1]": "asset://assets/images/douyin_emoji/qiubaobao.png",
  "[\u6c42\u62b1\u62b1]": "asset://assets/images/douyin_emoji/qiubaobao.png",
  "[\u7edd\u671b\u7684\u51dd\u89c6]":
      "asset://assets/images/douyin_emoji/zhoudongyudeningshi.png",
  "[\u4e0d\u5931\u793c\u8c8c\u7684\u5fae\u7b11]":
      "asset://assets/images/douyin_emoji/masichundeweixiao.png",
  "[\u4e0d\u770b]": "asset://assets/images/douyin_emoji/bukan.png",
  "[\u88c2\u5f00]": "asset://assets/images/douyin_emoji/liekai.png",
  "[\u5e72\u996d\u4eba]": "asset://assets/images/douyin_emoji/ganfanren.png",
  "[\u5e86\u795d]": "asset://assets/images/douyin_emoji/qingzhu.png",
  "[\u5410\u820c]": "asset://assets/images/douyin_emoji/tushe.png",
  "[\u5446\u65e0\u8f9c]": "asset://assets/images/douyin_emoji/daiwugu.png",
  "[\u767d\u773c]": "asset://assets/images/douyin_emoji/baiyan.png",
  "[\u718a\u5409]": "asset://assets/images/douyin_emoji/xiongji.png",
  "[\u732a\u5934]": "asset://assets/images/douyin_emoji/zhutou.png",
  "[\u51b7\u6f20]": "asset://assets/images/douyin_emoji/lengmo.png",
  "[\u5fae\u7b11\u888b\u9f20]":
      "asset://assets/images/douyin_emoji/weixiaodaishu.png",
  "[\u51dd\u89c6]": "asset://assets/images/douyin_emoji/ningshi.png",
  "[\u6697\u4e2d\u89c2\u5bdf]":
      "asset://assets/images/douyin_emoji/anzhongguancha.png",
  "[\u4e8c\u54c8]": "asset://assets/images/douyin_emoji/erha.png",
  "[\u83dc\u72d7]": "asset://assets/images/douyin_emoji/caigou.png",
  "[\u9ab7\u9ac5]": "asset://assets/images/douyin_emoji/kulou.png",
  "[\u9ed1\u8138]": "asset://assets/images/douyin_emoji/heilian.png",
  "[\u5c55\u5f00\u8bf4\u8bf4]":
      "asset://assets/images/douyin_emoji/zhankaishuoshuo.png",
  "[\u871c\u8702\u72d7]": "asset://assets/images/douyin_emoji/mifenggou.png",
  "[\u67f4\u72ac]": "asset://assets/images/douyin_emoji/huangchaiquan.png",
  "[\u6d41\u6c57]": "asset://assets/images/douyin_emoji/han.png",
  "[\u6c57]": "asset://assets/images/douyin_emoji/han.png",
  "[\u6478\u5934]": "asset://assets/images/douyin_emoji/motou.png",
  "[\u76b1\u7709]": "asset://assets/images/douyin_emoji/zhoumei.png",
  "[\u64e6\u6c57]": "asset://assets/images/douyin_emoji/cahan.png",
  "[\u7ea2\u8138]": "asset://assets/images/douyin_emoji/honglian.png",
  "[\u505a\u9b3c\u8138]": "asset://assets/images/douyin_emoji/zuoguilian.png",
  "[\u5f3a]": "asset://assets/images/douyin_emoji/qiang.png",
  "[\u5982\u82b1]": "asset://assets/images/douyin_emoji/ruhua.png",
  "[\u5410]": "asset://assets/images/douyin_emoji/tu.png",
  "[\u60ca\u559c]": "asset://assets/images/douyin_emoji/liangxi.png",
  "[\u6572\u6253]": "asset://assets/images/douyin_emoji/qiaoda.png",
  "[\u594b\u6597]": "asset://assets/images/douyin_emoji/fendou.png",
  "[\u5410\u5f69\u8679]": "asset://assets/images/douyin_emoji/tucaihong.png",
  "[\u5927\u54ed]": "asset://assets/images/douyin_emoji/daku.png",
  "[\u563f\u54c8]": "asset://assets/images/douyin_emoji/heiha.png",
  "[\u52a0\u597d\u53cb]": "asset://assets/images/douyin_emoji/jiahaoyou.png",
  "[\u60ca\u6050]": "asset://assets/images/douyin_emoji/jingkong.png",
  "[\u60ca\u8bb6]": "asset://assets/images/douyin_emoji/jingya.png",
  "[\u56e7]": "asset://assets/images/douyin_emoji/jiong.png",
  "[\u96be\u8fc7]": "asset://assets/images/douyin_emoji/nanguo.png",
  "[\u659c\u773c]": "asset://assets/images/douyin_emoji/xieyan.png",
  "[\u9634\u9669]": "asset://assets/images/douyin_emoji/yinxian.png",
  "[\u5de6\u54fc\u54fc]": "asset://assets/images/douyin_emoji/zuohengheng.png",
  "[\u53f3\u54fc\u54fc]": "asset://assets/images/douyin_emoji/youhengheng.png",
  "[\u60a0\u95f2]": "asset://assets/images/douyin_emoji/youxian.png",
  "[\u5492\u9a82]": "asset://assets/images/douyin_emoji/zhouma.png",
  "[\u5403\u74dc\u7fa4\u4f17]":
      "asset://assets/images/douyin_emoji/chiguaqunzhong.png",
  "[\u7eff\u5e3d\u5b50]": "asset://assets/images/douyin_emoji/lvmaozi.png",
  "[\u771f\u7684\u4f1a\u8c22]": "asset://assets/images/douyin_emoji/huixie.png",
  "[\u8fbe\u54a9]": "asset://assets/images/douyin_emoji/damie.png",
  "[\u6562\u6012\u4e0d\u6562\u8a00]":
      "asset://assets/images/douyin_emoji/gannubuganyan.png",
  "[\u6295\u964d]": "asset://assets/images/douyin_emoji/touxiang.png",
  "[\u6c42\u6c42\u4e86]": "asset://assets/images/douyin_emoji/qiuqiule.png",
  "[\u773c\u542b\u70ed\u6cea]":
      "asset://assets/images/douyin_emoji/yanhanrelei.png",
  "[\u53f9\u6c14]": "asset://assets/images/douyin_emoji/tanqi.png",
  "[\u597d\u5f00\u5fc3]": "asset://assets/images/douyin_emoji/haokaixin.png",
  "[\u4e0d\u662f\u5427]": "asset://assets/images/douyin_emoji/bushiba.png",
  "[\u52a8\u52a8\u8111\u5b50]":
      "asset://assets/images/douyin_emoji/dongdongnaozi.png",
  "[\u8868\u9762\u5fae\u7b11]":
      "asset://assets/images/douyin_emoji/biaomianweixiao.png",
  "[\u8868\u9762\u5472\u7259]":
      "asset://assets/images/douyin_emoji/biaomianciya.png",
  "[\u97a0\u8eac]": "asset://assets/images/douyin_emoji/jugong.png",
  "[\u8eba\u5e73]": "asset://assets/images/douyin_emoji/tangping.png",
  "[\u4e5d\u8f6c\u5927\u80a0]":
      "asset://assets/images/douyin_emoji/jiuzhuandachang.png",
  "[\u6572\u6728\u9c7c]": "asset://assets/images/douyin_emoji/qiaomuyu.png",
  "[\u4e0d\u4f60\u4e0d\u60f3]":
      "asset://assets/images/douyin_emoji/bunibuxiang.png",
  "[\u4e00\u5934\u4e71\u9ebb]":
      "asset://assets/images/douyin_emoji/yitouluanma.png",
  "[kisskiss]": "asset://assets/images/douyin_emoji/kisskiss.png",
  "[\u4f60\u4e0d\u5927\u884c]":
      "asset://assets/images/douyin_emoji/nibudaxing.png",
  "[\u5662\u4e70\u5c2c]": "asset://assets/images/douyin_emoji/omg.png",
  "[\u5b95\u673a]": "asset://assets/images/douyin_emoji/dangji.png",
  "[\u8fd8\u5f97\u662f\u6211]":
      "asset://assets/images/douyin_emoji/haideishiwo.png",
  "[6]": "asset://assets/images/douyin_emoji/6.png",
  "[\u8138\u75bc]": "asset://assets/images/douyin_emoji/lianteng.png",
  "[\u4ed6\u6025\u4e86]": "asset://assets/images/douyin_emoji/tajile.png",
  "[\u82e6\u6da9]": "asset://assets/images/douyin_emoji/kuse.png",
  "[\u901e\u5f3a\u843d\u6cea]":
      "asset://assets/images/douyin_emoji/chengqiangluolei.png",
  "[\u6c42\u673a\u4f4d-\u9ec4\u8138]":
      "asset://assets/images/douyin_emoji/huanglianqiujiwei.png",
  "[\u6c42\u673a\u4f4d1]": "asset://assets/images/douyin_emoji/qiujiwei1.png",
  "[\u6c42\u673a\u4f4d2]": "asset://assets/images/douyin_emoji/qiujiwei2.png",
  "[\u6c42\u673a\u4f4d3]": "asset://assets/images/douyin_emoji/qiujiwei3.png",
  "[\u6c42\u673a\u4f4d-ip]":
      "asset://assets/images/douyin_emoji/ipqiujiwei.png",
  "[\u52a9\u5a01]": "asset://assets/images/douyin_emoji/zhuwei.png",
  "[\u593a\u91d1]": "asset://assets/images/douyin_emoji/duojin.png",
  "[\u70b9\u8d5e]": "asset://assets/images/douyin_emoji/jingxuan.png",
  "[\u7ec6\u7ce0]": "asset://assets/images/douyin_emoji/xikang.png",
  "[\u7cbe\u9009]": "asset://assets/images/douyin_emoji/jingxuanzan.png",
  "[\u4e70\u4e70\u4e70]": "asset://assets/images/douyin_emoji/maimaimai.png",
  "[\u597d\u60f3\u8981]": "asset://assets/images/douyin_emoji/haoxiangyao.png",
  "[\u542b\u6cea\u5241\u624b]":
      "asset://assets/images/douyin_emoji/duoshou.png",
  "[\u5e26\u6211\u53bb]": "asset://assets/images/douyin_emoji/daiwoqu.png",
  "[\u597d\u60f3\u5403]": "asset://assets/images/douyin_emoji/haoxiangchi.png",
  "[\u5b89\u6392]": "asset://assets/images/douyin_emoji/anpai.png",
  "[\u7801\u4f4f]": "asset://assets/images/douyin_emoji/mazhu.png",
  "[\u79cd\u8349]": "asset://assets/images/douyin_emoji/zhongcao.png",
  "[\u4e0a\u94fe\u63a5]": "asset://assets/images/douyin_emoji/shanglianjie.png",
  "[\u5f3a\u58ee]": "asset://assets/images/douyin_emoji/jiayou.png",
  "[\u52a0\u6cb9]": "asset://assets/images/douyin_emoji/jiayou.png",
  "[\u78b0\u62f3]": "asset://assets/images/douyin_emoji/pengquan.png",
  "[OK]": "asset://assets/images/douyin_emoji/ok.png",
  "[ok]": "asset://assets/images/douyin_emoji/ok.png",
  "[\u51fb\u638c]": "asset://assets/images/douyin_emoji/jizhang.png",
  "[\u5de6\u4e0a]": "asset://assets/images/douyin_emoji/zuoshang.png",
  "[\u63e1\u624b]": "asset://assets/images/douyin_emoji/woshou.png",
  "[\u62b1\u62f3]": "asset://assets/images/douyin_emoji/baoquan.png",
  "[\u52fe\u5f15]": "asset://assets/images/douyin_emoji/gouyin.png",
  "[\u62f3\u5934]": "asset://assets/images/douyin_emoji/quantou.png",
  "[\u5f31]": "asset://assets/images/douyin_emoji/ruo.png",
  "[\u80dc\u5229]": "asset://assets/images/douyin_emoji/shengli.png",
  "[\u53f3\u8fb9]": "asset://assets/images/douyin_emoji/youbian.png",
  "[\u5de6\u8fb9]": "asset://assets/images/douyin_emoji/zuobian.png",
  "[\u8db3\u7403]": "asset://assets/images/douyin_emoji/zuqiu.png",
  "[\u7403\u978b]": "asset://assets/images/douyin_emoji/qiuxie.png",
  "[\u624b\u5957]": "asset://assets/images/douyin_emoji/shoutao.png",
  "[\u4e9a\u8fd0\u9f13\u638c]":
      "asset://assets/images/douyin_emoji/yayunguzhang.png",
  "[\u91d1\u724c]": "asset://assets/images/douyin_emoji/jinpai.png",
  "[\u624b\u82b1]": "asset://assets/images/douyin_emoji/shouhua.png",
  "[\u5634\u5507]": "asset://assets/images/douyin_emoji/kiss.png",
  "[kiss]": "asset://assets/images/douyin_emoji/kiss.png",
  "[\u5fc3\u788e]": "asset://assets/images/douyin_emoji/shangxin.png",
  "[\u51cb\u8c22]": "asset://assets/images/douyin_emoji/diaoxie.png",
  "[\u6124\u6012]": "asset://assets/images/douyin_emoji/fennu.png",
  "[\u5783\u573e]": "asset://assets/images/douyin_emoji/laji.png",
  "[\u5564\u9152]": "asset://assets/images/douyin_emoji/pijiu.png",
  "[\u5496\u5561]": "asset://assets/images/douyin_emoji/kafei.png",
  "[\u86cb\u7cd5]": "asset://assets/images/douyin_emoji/dangao.png",
  "[\u793c\u7269]": "asset://assets/images/douyin_emoji/liwu.png",
  "[\u6492\u82b1]": "asset://assets/images/douyin_emoji/sahua.png",
  "[\u52a0\u4e00]": "asset://assets/images/douyin_emoji/jiayi.png",
  "[\u51cf\u4e00]": "asset://assets/images/douyin_emoji/jianyi.png",
  "[okk]": "asset://assets/images/douyin_emoji/okk.png",
  "[V5]": "asset://assets/images/douyin_emoji/V5.png",
  "[\u7edd]": "asset://assets/images/douyin_emoji/jue.png",
  "[\u7ed9\u529b]": "asset://assets/images/douyin_emoji/geili.png",
  "[yes]": "asset://assets/images/douyin_emoji/yes.png",
  "[no]": "asset://assets/images/douyin_emoji/no.png",
  "[\u7ea2\u5305]": "asset://assets/images/douyin_emoji/hongbao.png",
  "[\u5c4e]": "asset://assets/images/douyin_emoji/shi.png",
  "[\u53d1]": "asset://assets/images/douyin_emoji/fa.png",
  "[\u6211\u592a\u96be\u4e86]":
      "asset://assets/images/douyin_emoji/wotainanle.png",
  "[18\u7981]": "asset://assets/images/douyin_emoji/18jin.png",
  "[\u70b8\u5f39]": "asset://assets/images/douyin_emoji/zhadan.png",
  "[\u53bb\u6c61\u7c89]": "asset://assets/images/douyin_emoji/quwufen.png",
  "[\u897f\u74dc]": "asset://assets/images/douyin_emoji/xigua.png",
  "[\u83dc\u5200]": "asset://assets/images/douyin_emoji/dao.png",
  "[\u5200]": "asset://assets/images/douyin_emoji/dao.png",
  "[\u5fc3]": "asset://assets/images/douyin_emoji/xin.png",
  "[\u4f24\u5fc3]": "asset://assets/images/douyin_emoji/shangxin.png",
  "[\u4fbf\u4fbf]": "asset://assets/images/douyin_emoji/shi.png",
  "[\u52a0\u9e21\u817f]": "asset://assets/images/douyin_emoji/jiajitui.png",
  "[\u6211\u9178\u4e86]": "asset://assets/images/douyin_emoji/wosuanle.png",
  "[\u63e1\u722a]": "asset://assets/images/douyin_emoji/wozhua.png",
  "[\u592a\u9633]": "asset://assets/images/douyin_emoji/taiyang.png",
  "[\u6708\u4eae]": "asset://assets/images/douyin_emoji/yueliang.png",
  "[\u7ed9\u8dea\u4e86]": "asset://assets/images/douyin_emoji/geiguile.png",
  "[\u8549\u7eff]": "asset://assets/images/douyin_emoji/jiaolv.png",
  "[\u624e\u5fc3]": "asset://assets/images/douyin_emoji/zhaxin.png",
  "[\u80e1\u74dc]": "asset://assets/images/douyin_emoji/hugua.png",
  "[yyds]": "asset://assets/images/douyin_emoji/yyds.png",
  "[emo]": "asset://assets/images/douyin_emoji/emo.png",
  "[\u5f00\u5fc3\u5154]": "asset://assets/images/douyin_emoji/kaixintu.png",
  "[\u62db\u8d22\u5154]": "asset://assets/images/douyin_emoji/zhaocaitu.png",
  "[\u5e74\u517d\u5154]": "asset://assets/images/douyin_emoji/nianshoutu.png",
  "[\u6253call]": "asset://assets/images/douyin_emoji/dacall.png",
  "[\u6813Q]": "asset://assets/images/douyin_emoji/shuanq.png",
  "[\u65e0\u8bed]": "asset://assets/images/douyin_emoji/wuyu.png",
  "[\u96ea\u4eba]": "asset://assets/images/douyin_emoji/xueren.png",
  "[\u96ea\u82b1]": "asset://assets/images/douyin_emoji/xuehua.png",
  "[\u5723\u8bde\u6811]": "asset://assets/images/douyin_emoji/shengdanshu.png",
  "[\u5e73\u5b89\u679c]": "asset://assets/images/douyin_emoji/pinganguo.png",
  "[\u5723\u8bde\u5e3d]": "asset://assets/images/douyin_emoji/shengdanmao.png",
  "[\u6c14\u7403]": "asset://assets/images/douyin_emoji/qiqiu.png",
  "[\u5e72\u676f]": "asset://assets/images/douyin_emoji/ganbei.png",
  "[\u70df\u82b1]": "asset://assets/images/douyin_emoji/yanhua.png",
  "[\u798f]": "asset://assets/images/douyin_emoji/fu.png",
  "[candy]": "asset://assets/images/douyin_emoji/candy.png",
  "[\u7cd6\u846b\u82a6]": "asset://assets/images/douyin_emoji/tanghulu.png",
  "[\u864e\u5934]": "asset://assets/images/douyin_emoji/hutou.png",
  "[\u997a\u5b50]": "asset://assets/images/douyin_emoji/jiaozi.png",
  "[\u97ad\u70ae]": "asset://assets/images/douyin_emoji/bianpao.png",
  "[\u5143\u5b9d]": "asset://assets/images/douyin_emoji/yuanbao.png",
  "[\u706f\u7b3c]": "asset://assets/images/douyin_emoji/denglong.png",
  "[\u9526\u9ca4]": "asset://assets/images/douyin_emoji/jinli.png",
  "[\u5de7\u514b\u529b]": "asset://assets/images/douyin_emoji/qiaokeli.png",
  "[\u6c64\u5706]": "asset://assets/images/douyin_emoji/tangyuan.png",
  "[\u60c5\u4e66]": "asset://assets/images/douyin_emoji/qingshu.png",
  "[iloveyou]": "asset://assets/images/douyin_emoji/iloveyou.png",
  "[\u6212\u6307]": "asset://assets/images/douyin_emoji/jiezhi.png",
  "[\u6d3e\u5bf9]": "asset://assets/images/douyin_emoji/sahua.png",
  "[\u8fc7\u5e74\u9f20]": "asset://assets/images/douyin_emoji/guonianshu.png",
  "[\u5c0f\u9ec4\u9e2d]": "asset://assets/images/douyin_emoji/xiaohuangya.png",
  "[\u68d2\u68d2\u7cd6]": "asset://assets/images/douyin_emoji/bangbangtang.png",
  "[\u7eb8\u98de\u673a]": "asset://assets/images/douyin_emoji/zhifeiji.png",
  "[\u5fc5\u80dc]": "asset://assets/images/douyin_emoji/bisheng.png",
  "[\u7cbd\u5b50]": "asset://assets/images/douyin_emoji/zongzi.png",
  "[\u8c61]": "asset://assets/images/douyin_emoji/xiang.png",
  "[\u5c0f\u7ea2\u82b1]": "asset://assets/images/douyin_emoji/xiaohonghua.png",
  "[\u7f57\u4e09\u70ae]": "asset://assets/images/douyin_emoji/luosanpao.png",
  "[\u6233\u4e00\u6233]": "asset://assets/images/douyin_emoji/chuoyichuo.png",
  "[\ud83c\udf8c]": "asset://assets/images/douyin_emoji/ribenguoqi.png",
  "[\u7231\u4e86\u7231\u4e86]":
      "asset://assets/images/douyin_emoji/aileaile.png",
  "[\u72d7\u5934\u574f\u7b11]":
      "asset://assets/images/douyin_emoji/goutouhuaixiao.png",
  "[\u7edd\u4e86]": "asset://assets/images/douyin_emoji/juele.png",
  "[\u5389\u5bb3\u4e86]": "asset://assets/images/douyin_emoji/lihaile.png",
  "[\u4e48\u4e48\u54d2]": "asset://assets/images/douyin_emoji/memeda.png",
  "[\u556a\u556a\u6253\u8138]":
      "asset://assets/images/douyin_emoji/papadalian.png",
  "[\u5c0f\u5fc3\u5fc3]": "asset://assets/images/douyin_emoji/xiaoxinxin.png",
  "[\u5728\u7ebf\u5403\u74dc]":
      "asset://assets/images/douyin_emoji/zaixianchigua.png",
  "[\u6765\u804a\u5929]": "asset://assets/images/douyin_emoji/lailiaotian.png",
  "[\u7535\u91cf\u8017\u5c3d]":
      "asset://assets/images/douyin_emoji/dianlianghaojin.png",
  "[\u522b\u53d1\u766b\u4e86]":
      "asset://assets/images/douyin_emoji/biefadianle.png",
  "[nonono]": "asset://assets/images/douyin_emoji/nonono.png",
  "[\u770b\u8d74\u5c71\u6d77]":
      "asset://assets/images/douyin_emoji/kanfushanhai.png",
  "[\u656c\u793c]": "asset://assets/images/douyin_emoji/jingli.png",
  "[\u7ea2\u65d7]": "asset://assets/images/douyin_emoji/hongqi.png",
  "[\u5403\u6708\u997c]": "asset://assets/images/douyin_emoji/chiyuebing.png",
  "[\u7389\u5154]": "asset://assets/images/douyin_emoji/yutu.png",
  "[\u659c\u5218\u6d77]": "asset://assets/images/douyin_emoji/xieliuhai.png",
  "[\u7eff\u53d1]": "asset://assets/images/douyin_emoji/lvfa.png",
  "[\u9ec4\u53d1]": "asset://assets/images/douyin_emoji/huangfa.png",
  "[\u88c5\u9177]": "asset://assets/images/douyin_emoji/zhuangku.png",
  "[\u7c89\u53d1]": "asset://assets/images/douyin_emoji/fenfa.png",
  "[\u6c42\u597d\u8fd0]": "asset://assets/images/douyin_emoji/qiuhaoyun.png",
  "[\u8d85\u4eba]": "asset://assets/images/douyin_emoji/chaoren.png",
  "[\u5c0f\u4e11]": "asset://assets/images/douyin_emoji/xiaochou.png",
  "[\u5c0f\u9b3c]": "asset://assets/images/douyin_emoji/xiaogui.png",
  "[\u96ea\u7403]": "asset://assets/images/douyin_emoji/xueqiu.png",
  "[\u559c\u7f8a\u7f8a]": "asset://assets/images/douyin_emoji/xiyangyang.png",
  "[\u7f8e\u7f8a\u7f8a]": "asset://assets/images/douyin_emoji/meiyangyang.png",
  "[\u61d2\u7f8a\u7f8a]": "asset://assets/images/douyin_emoji/lanyangyang.png",
  "[\u6696\u7f8a\u7f8a]": "asset://assets/images/douyin_emoji/nuanyangyang.png",
  "[\u6cb8\u7f8a\u7f8a]": "asset://assets/images/douyin_emoji/feiyangyang.png",
  "[\u7070\u592a\u72fc]": "asset://assets/images/douyin_emoji/huitailang.png",
  "[\u7ea2\u592a\u72fc]": "asset://assets/images/douyin_emoji/hongtailang.png",
  "[\u4e3e\u91cd]": "asset://assets/images/douyin_emoji/juzhong.png",
  "[\u4e52\u4e53\u7403]": "asset://assets/images/douyin_emoji/pingpangqiu.png",
  "[\u7bee\u7403]": "asset://assets/images/douyin_emoji/lanqiu.png",
  "[\u6fc0\u60c5]": "asset://assets/images/douyin_emoji/jiqing.png",
  "[\u5956\u724c]": "asset://assets/images/douyin_emoji/jiangpai.png",
  "[\u6bdb\u96ea\u4eba]": "asset://assets/images/douyin_emoji/maoxueren.png",
  "[\u6bdb\u624b\u5957]": "asset://assets/images/douyin_emoji/maoshoutao.png",
  "[\u706b\u9505]": "asset://assets/images/douyin_emoji/huoguo.png",
  "[\u5976\u8336]": "asset://assets/images/douyin_emoji/naicha.png",
  "[\u8ffd\u5267]": "asset://assets/images/douyin_emoji/zhuiju.png",
  "[\u4e0b\u96ea]": "asset://assets/images/douyin_emoji/xiaxue.png",
  "[\u5c3c\u514b]": "asset://assets/images/douyin_emoji/nike.png",
  "[\u6731\u8fea]": "asset://assets/images/douyin_emoji/zhudi.png",
  "[\u76d6\u745e]": "asset://assets/images/douyin_emoji/gairui.png",
  "[\u590f\u5947\u7f8a]": "asset://assets/images/douyin_emoji/xiaqiyang.png",
  "[\u9a6c\u5e02\u957f]": "asset://assets/images/douyin_emoji/mashizhang.png",
  "[\u7ea2\u5934\u5dfe]": "asset://assets/images/douyin_emoji/hongtoujin.png",
  "[\u84dd\u5934\u5dfe]": "asset://assets/images/douyin_emoji/lantoujin.png",
  "[\u7b11\u6389\u7259]": "asset://assets/images/douyin_emoji/xiaodiaoya.png",
  "[\u6211\u770b\u884c]": "asset://assets/images/douyin_emoji/wokanxing.png",
  "[\u519b\u5927\u8863]": "asset://assets/images/douyin_emoji/jundayi.png",
  "[\u51b0\u7cd6\u846b\u82a6]":
      "asset://assets/images/douyin_emoji/bingtanghulu.png",
  "[\u606d\u559c\u53d1\u8d22]":
      "asset://assets/images/douyin_emoji/gongxifacai_emoji.png",
  "[\u7ea2\u5305\u62ff\u6765]":
      "asset://assets/images/douyin_emoji/hongbaonalai_emoji.png",
  "[\u8c22\u8c22]": "asset://assets/images/douyin_emoji/xiexie_emoji.png",
  "[\u8d34\u8d34\u7ea2\u5305]":
      "asset://assets/images/douyin_emoji/tietiehongbao_emoji.png",
  "[wink]": "asset://assets/images/douyin_emoji/wink_emoji.png",
  "[\u5e72\u996d]": "asset://assets/images/douyin_emoji/ganfan_emoji.png",
  "[\u66b4\u66b4\u9f99]":
      "asset://assets/images/douyin_emoji/baobaolong_emoji.png",
  "[\u5927\u5723\u5403\u6843]":
      "asset://assets/images/douyin_emoji/dashengchitao.png",
  "[\u7334\u738b\u800d\u68cd]":
      "asset://assets/images/douyin_emoji/houwangshuagun_emoji.png",
  "[\u5f3c\u9a6c\u6e29]": "asset://assets/images/douyin_emoji/bimawen.png",
  "[\u592a\u767d\u91d1\u661f]":
      "asset://assets/images/douyin_emoji/taibaijinxing_emoji.png",
  "[\u4ed9\u5973\u6563\u82b1]":
      "asset://assets/images/douyin_emoji/xiannvsanhua_emoji.png",
  "[\u5927\u5723\u5c0f\u5e99]":
      "asset://assets/images/douyin_emoji/dashengxiaomiao.png",
  "[\u5927\u5a03]": "asset://assets/images/douyin_emoji/dawa_emoji.png",
  "[\u4e8c\u5a03]": "asset://assets/images/douyin_emoji/erwa_emoji.png",
  "[\u4e09\u5a03]": "asset://assets/images/douyin_emoji/sanwa_emoji.png",
  "[\u56db\u5a03]": "asset://assets/images/douyin_emoji/siwa_emoji.png",
  "[\u4e94\u5a03]": "asset://assets/images/douyin_emoji/wuwa_emoji.png",
  "[\u4e03\u5a03]": "asset://assets/images/douyin_emoji/qiwa_emoji.png",
  "[\u7237\u7237]": "asset://assets/images/douyin_emoji/yeye_emoji.png",
  "[\u59b2\u5df1]": "asset://assets/images/douyin_emoji/daji.png",
  "[\u5b89\u742a\u62c9]": "asset://assets/images/douyin_emoji/anqila.png",
  "[\u9c81\u73ed\u4e03\u53f7]":
      "asset://assets/images/douyin_emoji/lubanqihao.png",
  "[\u9a6c\u53ef\u6ce2\u7f57]":
      "asset://assets/images/douyin_emoji/makeboluo.png",
  "[\u7476]": "asset://assets/images/douyin_emoji/yao.png",
  "[\u6f9c]": "asset://assets/images/douyin_emoji/lan.png",
  "[\u5c0f\u4e54]": "asset://assets/images/douyin_emoji/xiaoqiao.png",
  "[\u5149\u5934\u5f3a]":
      "asset://assets/images/douyin_emoji/guangtouqiang_emoji.png",
  "[\u718a\u5927]": "asset://assets/images/douyin_emoji/xiongda.png",
  "[\u718a\u4e8c]": "asset://assets/images/douyin_emoji/xionger.png",
  "[\u5e74\u5e74]": "asset://assets/images/douyin_emoji/niannian.png",
  "[\u5409\u5409\u56fd\u738b]":
      "asset://assets/images/douyin_emoji/\u5409\u5409\u56fd\u738b_emoji.png",
  "[\u6bdb\u6bdb]": "asset://assets/images/douyin_emoji/maomao_emoji.png",
  "[\u7ea2\u718a\u8304\u8304]":
      "asset://assets/images/douyin_emoji/hongxiongqieqie.png",
  "[\u6c99\u4e18\u4e4b\u4e3b]":
      "asset://assets/images/douyin_emoji/shaqiuzhizhu.png",
  "[\u5343\u91d1\u6dd1\u732b]":
      "asset://assets/images/douyin_emoji/qianjinshumao.png",
  "[\u68a6\u5e7b\u706b\u7bad]":
      "asset://assets/images/douyin_emoji/menghuanhuojian.png",
  "[\u96ea\u56fd\u5e7b\u68a6]":
      "asset://assets/images/douyin_emoji/xueguohuanmeng.png",
  "[\u9a6c\u5361\u9f99]": "asset://assets/images/douyin_emoji/makalong.png",
  "[\u8d85\u7ea7\u7231]": "asset://assets/images/douyin_emoji/chaojiai.png",
  "[\u548c\u4f60\u804a\u5929]":
      "asset://assets/images/douyin_emoji/heniliaotian.png",
  "[\u53d1\u5c04\u7231\u5fc3]":
      "asset://assets/images/douyin_emoji/fasheaixin.png",
  "[\u662f\u5fc3\u52a8\u554a]":
      "asset://assets/images/douyin_emoji/shixindonga.png",
  "[\u5077\u5077\u7231]": "asset://assets/images/douyin_emoji/toutouai.png",
  "[\u6bd4\u4e2a\u5fc3]": "asset://assets/images/douyin_emoji/bigexin.png",
  "[\u7c89\u8272\u7231\u5fc3]":
      "asset://assets/images/douyin_emoji/fenseaixin.png",
  "[\u5e78\u8fd0\u8349]": "asset://assets/images/douyin_emoji/xingyuncao.png",
  "[\u4e0a\u5cb8]": "asset://assets/images/douyin_emoji/shangan.png",
  "[\u8003\u8fd0\u7206\u68da]":
      "asset://assets/images/douyin_emoji/kaoyunbaopeng.png",
  "[\u91d1\u699c\u9898\u540d]":
      "asset://assets/images/douyin_emoji/jinbangtiming.png",
  "[\u8bb8\u613f]": "asset://assets/images/douyin_emoji/xuyuan.png",
  "[\u6bd5\u4e1a\u5566]": "asset://assets/images/douyin_emoji/biyela.png",
  "[\u7c73\u5947]": "asset://assets/images/douyin_emoji/miqi.png",
  "[\u7c73\u59ae]": "asset://assets/images/douyin_emoji/mini.png",
  "[\u5510\u8001\u9e2d]": "asset://assets/images/douyin_emoji/tanglaoya.png",
  "[\u9edb\u4e1d]": "asset://assets/images/douyin_emoji/daisi.png",
  "[\u9ad8\u98de]": "asset://assets/images/douyin_emoji/gaofei.png",
  "[\u5e03\u9c81\u6258]": "asset://assets/images/douyin_emoji/bulutuo.png",
  "[\u5947\u5947\u8482\u8482]":
      "asset://assets/images/douyin_emoji/qiqididi.png",
  "[\u6fc0\u60c5\u5f00\u9ea6]":
      "asset://assets/images/douyin_emoji/jiqingkaimai.png",
  "[\u8d70\u4e00\u4e2a]": "asset://assets/images/douyin_emoji/zouyige.png",
  "[\u55e8\u8d77\u6765]": "asset://assets/images/douyin_emoji/haiqilai.png",
  "[\u7ea2\u724c\u5927\u5e08]":
      "asset://assets/images/douyin_emoji/hongpaidashi.png",
  "[\u8fdb\u7403\u5566]": "asset://assets/images/douyin_emoji/jinqiula.png",
  "[\u88ab\u7a9d\u770b\u7403]":
      "asset://assets/images/douyin_emoji/beiwokanqiu.png",
  "[\u5a01\u9f99]": "asset://assets/images/douyin_emoji/weilong.png",
  "[\u9a87\u722a]": "asset://assets/images/douyin_emoji/haizhua.png",
  "[\u8702\u533b]": "asset://assets/images/douyin_emoji/fengyi.png",
  "[\u9732\u5a1c]": "asset://assets/images/douyin_emoji/luna.png",
  "[\u7ea2\u72fc]": "asset://assets/images/douyin_emoji/new_emoji.png",
  "[\u4e4c\u9c81\u9c81]": "asset://assets/images/douyin_emoji/wululu.png",
  "[\u7267\u7f8a\u4eba]": "asset://assets/images/douyin_emoji/muyangren.png",
  "[\u9001\u73ab\u7470]": "asset://assets/images/douyin_emoji/songmeigui.png",
  "[\u5fc3\u52a8]": "asset://assets/images/douyin_emoji/xindong.png",
  "[\u5192\u6c57]": "asset://assets/images/douyin_emoji/maohan.png",
  "[\u770b\u620f]": "asset://assets/images/douyin_emoji/kanxi.png",
  "[\u5c0f\u54ed\u5305]": "asset://assets/images/douyin_emoji/xiaokubao.png",
  "[\u767b\u573a]": "asset://assets/images/douyin_emoji/dengchang.png",
};
