// Generated. Do not edit by hand.
// Kuaishou Android client: 14.7.10.49551
// Source: https://apissl.kuaishou.com/rest/n/emotion/package/list/v2
// Generated at: 2026-08-12T14:38:01+08:00
library;

const String kuaishouMobileEmojiClientVersion =
    "14.7.10.49551";
const String kuaishouMobileEmojiSource =
    "https://apissl.kuaishou.com/rest/n/emotion/package/list/v2";
const String kuaishouMobileEmojiGeneratedAt =
    "2026-08-12T14:38:01+08:00";
const int kuaishouMobileEmojiAssetCount = 258;

const Map<String, String> kuaishouMobileEmojiAssets = {
  "[捂脸]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc2MDIxMjAydGhpcmRfcGFydHlfczEyOTY3NDc0NTcucG5nEIfN1y8.webp",
  "[龇牙]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1OTc4MTQ0dGhpcmRfcGFydHlfczEyOTY3NDY4ODIucG5nEIfN1y8.webp",
  "[大哭]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMDI4OTQwdGhpcmRfcGFydHlfczEyOTY2OTYwMzMucG5nEIfN1y8.webp",
  "[赞]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMTUzNDQ5dGhpcmRfcGFydHlfczEyOTY2NTI4ODEucG5nEIfN1y8.webp",
  "[奸笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc2MDU5ODE2dGhpcmRfcGFydHlfczEyOTY3NDgwNTIucG5nEIfN1y8.webp",
  "[微笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1ODQwMDczdGhpcmRfcGFydHlfczEyOTY3NDUyNTQucG5nEIfN1y8.webp",
  "[生气]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NjEwNDg5dGhpcmRfcGFydHlfczEyOTY3NDI0MTcucG5nEIfN1y8.webp",
  "[笑哭]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxNTU0NzgxdGhpcmRfcGFydHlfczEyOTY2OTk5NzEucG5nEIfN1y8.webp",
  "[憨笑哪吒]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3ODU0NTUzdGhpcmRfcGFydHlfczIxOTY1ODk4NzIucG5nEIfN1y8.webp",
  "[色]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMjMxNzcwdGhpcmRfcGFydHlfczEyOTY3MDQ4NDYucG5nEIfN1y8.webp",
  "[爱心]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY1ODc2MDk0dGhpcmRfcGFydHlfczEyOTY2Njc4NTIucG5nEIfN1y8.webp",
  "[玫瑰]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMTQyNjM1dGhpcmRfcGFydHlfczEyOTY2NTY2MTIucG5nEIfN1y8.webp",
  "[柴犬]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNTYyMzY2dGhpcmRfcGFydHlfczEyOTY2NTA1MDUucG5nEIfN1y8.webp",
  "[尊嘟假嘟]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3MDU1NDUwdGhpcmRfcGFydHlfczIwNDA2NDIzMzYucG5nEIfN1y8.webp",
  "[做不完]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4MDYxMjQydGhpcmRfcGFydHlfczIwNDA2NTEzNDUucG5nEIfN1y8.webp",
  "[哼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1OTM1OTE3dGhpcmRfcGFydHlfczEyOTY3NDY0MDcucG5nEIfN1y8.webp",
  "[哦]":
      "https://p66-plat.ndcjl.com/bs2/emotion/1704775888472third_party_s1296745888.png",
  "[猪猪]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3MzcyODI4dGhpcmRfcGFydHlfczIxOTY1ODY3ODQucG5nEIfN1y8.webp",
  "[略略略]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE2NzQyMjc0dGhpcmRfcGFydHlfczIwNDA2Mzk1MDgucG5nEIfN1y8.webp",
  "[裂开]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg4OTUxMzI1dGhpcmRfcGFydHlfczEyOTY4NDU0MTAucG5nEIfN1y8.webp",
  "[翻白眼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MDM3MTEydGhpcmRfcGFydHlfczEyOTY4NDYwMjYucG5nEIfN1y8.webp",
  "[666]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzNDQ3NTA1dGhpcmRfcGFydHlfczEyOTY2NTc0ODkucG5nEIfN1y8.webp",
  "[落泪]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NjU3OTA5dGhpcmRfcGFydHlfczEyOTY2ODE5MDYucG5nEIfN1y8.webp",
  "[难过至极]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MDc4OTgwdGhpcmRfcGFydHlfczEyOTY4NDYyMzYucG5nEIfN1y8.webp",
  "[流鼻血]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MzMwMTgzdGhpcmRfcGFydHlfczEyOTY2ODAwMzcucG5nEIfN1y8.webp",
  "[惊恐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwNjUwNjY0dGhpcmRfcGFydHlfczEyOTY2OTM3ODEucG5nEIfN1y8.webp",
  "[亲亲]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwNDUzNDM5dGhpcmRfcGFydHlfczEyOTY2OTI2MjQucG5nEIfN1y8.webp",
  "[哭笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzAyNjc4NzA3dGhpcmRfcGFydHlfczEyOTU5NzIzNjYucG5nEIfN1y8.webp",
  "[调皮]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1Nzk4NjQwdGhpcmRfcGFydHlfczEyOTY3NDQ2OTEucG5nEIfN1y8.webp",
  "[难过]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NTYwNTQzdGhpcmRfcGFydHlfczEyOTY3NDE4MDUucG5nEIfN1y8.webp",
  "[抱抱]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2NDc0NTk2dGhpcmRfcGFydHlfczEyOTY2NzA1MzYucG5nEIfN1y8.webp",
  "[都市丽人]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3NDM1MDAydGhpcmRfcGFydHlfczIxOTY1ODcxMzgucG5nEIfN1y8.webp",
  "[呕吐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMTE4OTc5dGhpcmRfcGFydHlfczEyOTY3MDM4MTAucG5nEIfN1y8.webp",
  "[疑问]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NjYwMzQydGhpcmRfcGFydHlfczEyOTY3NDI5OTIucG5nEIfN1y8.webp",
  "[偷笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NzA2NjcydGhpcmRfcGFydHlfczEyOTY2ODI0MjgucG5nEIfN1y8.webp",
  "[汗]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMTc3MzEwdGhpcmRfcGFydHlfczEyOTY3MDQyODMucG5nEIfN1y8.webp",
  "[火]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzNTA0MzU5dGhpcmRfcGFydHlfczEyOTY2NTc2NTkucG5nEIfN1y8.webp",
  "[呆住]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NzU1Njc1dGhpcmRfcGFydHlfczEyOTY3NDQxOTgucG5nEIfN1y8.webp",
  "[比心]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxODEwMjI4dGhpcmRfcGFydHlfczEyOTY2NTEzNzUucG5nEIfN1y8.webp",
  "[发呆]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg4MDI1NDQwdGhpcmRfcGFydHlfczEyOTY4MzkyMTUucG5nEIfN1y8.webp",
  "[吹口哨]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3NDIyMjE0dGhpcmRfcGFydHlfczIwNDA2NDUzMTUucG5nEIfN1y8.webp",
  "[上吊]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3OTM1MjIzdGhpcmRfcGFydHlfczEyOTY4Mzg3NDUucG5nEIfN1y8.webp",
  "[强颜欢笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg4OTk3MzA2dGhpcmRfcGFydHlfczEyOTY4NDU4MTcucG5nEIfN1y8.webp",
  "[祈祷]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyOTE4MjczdGhpcmRfcGFydHlfczEyOTY2NTU3NjUucG5nEIfN1y8.webp",
  "[心心]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMzQ2Mjc2dGhpcmRfcGFydHlfczEyOTY3MDU3NjMucG5nEIfN1y8.webp",
  "[摸鱼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MjE3MzUydGhpcmRfcGFydHlfczEyOTY4NDc0MTIucG5nEIfN1y8.webp",
  "[委屈]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxNDUwNjk0dGhpcmRfcGFydHlfczEyOTY2OTkwNzAucG5nEIfN1y8.webp",
  "[困死了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4MzMyOTE5dGhpcmRfcGFydHlfczIwNDA2NTM5MzcucG5nEIfN1y8.webp",
  "[拽姐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3NTA3NTg2dGhpcmRfcGFydHlfczIxOTY1ODc1NTIucG5nEIfN1y8.webp",
  "[早啊]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3OTU0MzQzdGhpcmRfcGFydHlfczIzMDMzODU1OTcucG5nEIfN1y8.webp",
  "[做作业]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3OTM4NzIxdGhpcmRfcGFydHlfczIwNDA2NTAyODYucG5nEIfN1y8.webp",
  "[挑逗]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NjAwNDU3dGhpcmRfcGFydHlfczEyOTY2ODE1MjkucG5nEIfN1y8.webp",
  "[我看行]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5MTUzNzQ4dGhpcmRfcGFydHlfczIwNDA2NjMyNjMucG5nEIfN1y8.webp",
  "[头盔]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxNjU0NTI0dGhpcmRfcGFydHlfczEyOTY3MDA2MTEucG5nEIfN1y8.webp",
  "[爱你]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2ODE1MzE0dGhpcmRfcGFydHlfczEyOTY2NzE4NTcucG5nEIfN1y8.webp",
  "[羞涩]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMjg5NzkwdGhpcmRfcGFydHlfczEyOTY3MDUzMjQucG5nEIfN1y8.webp",
  "[大便]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMjg5Njc3dGhpcmRfcGFydHlfczEyOTY2NTcxMTIucG5nEIfN1y8.webp",
  "[装傻]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2OTQ1MDk0dGhpcmRfcGFydHlfczEyOTY2NzI3MTQucG5nEIfN1y8.webp",
  "[贴贴]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3MzE2OTkwdGhpcmRfcGFydHlfczIwNDA2NDQ0NjQucG5nEIfN1y8.webp",
  "[心碎]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3NjMzNjU1dGhpcmRfcGFydHlfczIzMDMzODQ1OTAucG5nEIfN1y8.webp",
  "[出去丸]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4MjEyNjY2dGhpcmRfcGFydHlfczIwNDA2NTI2MjkucG5nEIfN1y8.webp",
  "[憨笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MDU0MjIzdGhpcmRfcGFydHlfczEyOTY2Nzg1MDAucG5nEIfN1y8.webp",
  "[辣眼睛]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5NDQzMjgzdGhpcmRfcGFydHlfczEyOTY4NDg4MjIucG5nEIfN1y8.webp",
  "[元气满满]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3NjA2NDM2dGhpcmRfcGFydHlfczEyOTY4MzY5MDgucG5nEIfN1y8.webp",
  "[亲吻]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3NzU2MDU5dGhpcmRfcGFydHlfczIxOTY1ODkxMjUucG5nEIfN1y8.webp",
  "[奸笑哪吒]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg4MTE2NTExdGhpcmRfcGFydHlfczIxOTY1OTEzODkucG5nEIfN1y8.webp",
  "[网红猫]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMzA3MjYydGhpcmRfcGFydHlfczEyOTY2NDk0ODcucG5nEIfN1y8.webp",
  "[ok]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5OTk5MDgzdGhpcmRfcGFydHlfczEyOTY4NTI2NDgucG5nEIfN1y8.webp",
  "[红脸哪吒]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3OTkzMDY1dGhpcmRfcGFydHlfczIxOTY1OTA4MjQucG5nEIfN1y8.webp",
  "[熬夜]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg2ODUzNTkydGhpcmRfcGFydHlfczEyOTY4MzE5NDgucG5nEIfN1y8.webp",
  "[愉快]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxNDk4MzEydGhpcmRfcGFydHlfczEyOTY2OTkzODIucG5nEIfN1y8.webp",
  "[让人头大]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4ODc0NzI4dGhpcmRfcGFydHlfczIwNDA2NjAwNDMucG5nEIfN1y8.webp",
  "[你好呀]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE2MzIwNTYydGhpcmRfcGFydHlfczIwNDA2MzY0MDEucG5nEIfN1y8.webp",
  "[雾霾]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2NTk0NTkxdGhpcmRfcGFydHlfczEyOTY2NzA5ODgucG5nEIfN1y8.webp",
  "[可怜]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5ODQ5NzEydGhpcmRfcGFydHlfczEyOTY2ODkyODEucG5nEIfN1y8.webp",
  "[错了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3NTM0MjY2dGhpcmRfcGFydHlfczIzMDMzODQ0MTEucG5nEIfN1y8.webp",
  "[抠鼻]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5ODAyNjM4dGhpcmRfcGFydHlfczEyOTY2ODkwMTIucG5nEIfN1y8.webp",
  "[进度0]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5Nzk3NDA0dGhpcmRfcGFydHlfczIwNDA2NzI5NDAucG5nEIfN1y8.webp",
  "[撇嘴]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NTE3NDg2dGhpcmRfcGFydHlfczEyOTY3NDEzODAucG5nEIfN1y8.webp",
  "[猪头]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwOTUyNTM2dGhpcmRfcGFydHlfczEyOTY2NDgzMDkucG5nEIfN1y8.webp",
  "[囧]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5NjI2MzI1dGhpcmRfcGFydHlfczEyOTY2ODc4NjMucG5nEIfN1y8.webp",
  "[吃瓜]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MjIwNzIxdGhpcmRfcGFydHlfczEyOTY2Nzk1ODEucG5nEIfN1y8.webp",
  "[猪蹄]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNzcxMzA0dGhpcmRfcGFydHlfczEyOTY2NDgwNTgucG5nEIfN1y8.webp",
  "[抱拳]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzkwMTEzMjIxdGhpcmRfcGFydHlfczEyOTY4NTM0NDMucG5nEIfN1y8.webp",
  "[怒言]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3ODkwMDIxdGhpcmRfcGFydHlfczEyOTY2Nzc2NzgucG5nEIfN1y8.webp",
  "[福字]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNTIxOTA2dGhpcmRfcGFydHlfczEyOTY2NTQzOTAucG5nEIfN1y8.webp",
  "[求求了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5Mjg5NTgwdGhpcmRfcGFydHlfczEyOTY4NDc5NTcucG5nEIfN1y8.webp",
  "[惊讶]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NDQ1NjY2dGhpcmRfcGFydHlfczEyOTY3NDA0MjAucG5nEIfN1y8.webp",
  "[对不起]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4Nzc1MjkzdGhpcmRfcGFydHlfczIwNDA2NTkwMzUucG5nEIfN1y8.webp",
  "[扎心]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMzkxOTIxdGhpcmRfcGFydHlfczEyOTY2NTczNDUucG5nEIfN1y8.webp",
  "[优秀]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzU5NjYwMTM3dGhpcmRfcGFydHlfczEyOTY2NDUzMDEucG5nEIfN1y8.webp",
  "[不说]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMDE0Njc4dGhpcmRfcGFydHlfczEyOTY2NDg2MjMucG5nEIfN1y8.webp",
  "[菜刀]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyODE5MTczdGhpcmRfcGFydHlfczEyOTY2NTU1MjIucG5nEIfN1y8.webp",
  "[对号]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzMDU1NjQ5dGhpcmRfcGFydHlfczEyOTY4MDc0NDcucG5nEIfN1y8.webp",
  "[平底锅]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5Njg3NTQydGhpcmRfcGFydHlfczEyOTY2ODgyNzAucG5nEIfN1y8.webp",
  "[旋转]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MTE3NTYwdGhpcmRfcGFydHlfczEyOTY2Nzg3ODMucG5nEIfN1y8.webp",
  "[钱]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMzE2MzgwdGhpcmRfcGFydHlfczEyOTY2NTMzMTkucG5nEIfN1y8.webp",
  "[出魂儿]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NDQxMTMwdGhpcmRfcGFydHlfczEyOTY2NzUyODYucG5nEIfN1y8.webp",
  "[黑脸问]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MTY4NzkxdGhpcmRfcGFydHlfczEyOTY2NzkyMzQucG5nEIfN1y8.webp",
  "[恋爱柴]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3MTYyMDI1dGhpcmRfcGFydHlfczIxOTY1ODU2MTcucG5nEIfN1y8.webp",
  "[冷汗]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwMzk1MDI4dGhpcmRfcGFydHlfczEyOTY2OTIyMzEucG5nEIfN1y8.webp",
  "[不看]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMTM2ODY1dGhpcmRfcGFydHlfczEyOTY2NDkwNjEucG5nEIfN1y8.webp",
  "[进度99]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5OTY4NjQydGhpcmRfcGFydHlfczIwNDA2NzUzMDAucG5nEIfN1y8.webp",
  "[emo]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg2OTQzNzc0dGhpcmRfcGFydHlfczEyOTY4MzI0NTgucG5nEIfN1y8.webp",
  "[不听]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMDc0ODMxdGhpcmRfcGFydHlfczEyOTY2NDg4MDcucG5nEIfN1y8.webp",
  "[有八卦]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3MTkzNTEzdGhpcmRfcGFydHlfczIwNDA2NDM1OTMucG5nEIfN1y8.webp",
  "[红脸蛋]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwNTkxMTUwdGhpcmRfcGFydHlfczEyOTY2OTM0OTkucG5nEIfN1y8.webp",
  "[哼唧哪吒]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3OTExMzkxdGhpcmRfcGFydHlfczIxOTY1OTAyMDcucG5nEIfN1y8.webp",
  "[ILoveU]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTIwMDYyODIydGhpcmRfcGFydHlfczIwNDA2NzY0ODcucG5nEIfN1y8.webp",
  "[天啊]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3MjcxMzM1dGhpcmRfcGFydHlfczEyOTY2NzQyMzkucG5nEIfN1y8.webp",
  "[偷瞄]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MjcwMjQ5dGhpcmRfcGFydHlfczEyOTY2Nzk4MjcucG5nEIfN1y8.webp",
  "[上号]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4NTU5OTk4dGhpcmRfcGFydHlfczIwNDA2NTY4MjEucG5nEIfN1y8.webp",
  "[白眼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMzQ2MTM1dGhpcmRfcGFydHlfczEyOTY2OTg2NjAucG5nEIfN1y8.webp",
  "[单身哈]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg2ODUxMjYxdGhpcmRfcGFydHlfczIxOTY1ODM3MzUucG5nEIfN1y8.webp",
  "[摸头]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2NjU3Mzk1dGhpcmRfcGFydHlfczEyOTY2NzExOTgucG5nEIfN1y8.webp",
  "[晕]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwMDM4MDcydGhpcmRfcGFydHlfczEyOTY2OTAzMzYucG5nEIfN1y8.webp",
  "[吐彩虹]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3OTk0Njc0dGhpcmRfcGFydHlfczEyOTY2NzgzMjcucG5nEIfN1y8.webp",
  "[欢迎]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMDQ4MzQzdGhpcmRfcGFydHlfczEyOTY2NTI1MDQucG5nEIfN1y8.webp",
  "[尴尬]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NTA2NTY5dGhpcmRfcGFydHlfczEyOTY2NzU1MjgucG5nEIfN1y8.webp",
  "[先睡了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg2OTEwMzM2dGhpcmRfcGFydHlfczEyOTY4MzIyMDkucG5nEIfN1y8.webp",
  "[美滋滋]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MTMzMTc2dGhpcmRfcGFydHlfczEyOTY4NDY3MTAucG5nEIfN1y8.webp",
  "[握手]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzkwMDQ2NTUydGhpcmRfcGFydHlfczEyOTY4NTI4NTAucG5nEIfN1y8.webp",
  "[骷髅]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4ODg0MDYxdGhpcmRfcGFydHlfczEyOTY2ODM0NTgucG5nEIfN1y8.webp",
  "[快哭了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5MzQ3MTA4dGhpcmRfcGFydHlfczEyOTY2ODYyODQucG5nEIfN1y8.webp",
  "[发财]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3Njg1MzA5dGhpcmRfcGFydHlfczIxOTY1ODg2NTIucG5nEIfN1y8.webp",
  "[鄙视]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMzk1NDU3dGhpcmRfcGFydHlfczEyOTY2OTg4OTEucG5nEIfN1y8.webp",
  "[星星眼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzc1NzA1MjgzdGhpcmRfcGFydHlfczEyOTY3NDM1OTEucG5nEIfN1y8.webp",
  "[想吃]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NjY3ODQ5dGhpcmRfcGFydHlfczEyOTY2NzY0NDkucG5nEIfN1y8.webp",
  "[正能量]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTIwMTYxMzg0dGhpcmRfcGFydHlfczIwNDA2NzgyNzQucG5nEIfN1y8.webp",
  "[打call]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5MjQ3MTE3dGhpcmRfcGFydHlfczIwNDA2NjQ2NjAucG5nEIfN1y8.webp",
  "[坏笑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5OTA2MTU3dGhpcmRfcGFydHlfczEyOTY2ODk1MTUucG5nEIfN1y8.webp",
  "[稍等]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5MDE3NDAwdGhpcmRfcGFydHlfczIwNDA2NjE3MjkucG5nEIfN1y8.webp",
  "[吓]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3OTgxOTU3dGhpcmRfcGFydHlfczEyOTY4MzkwMjgucG5nEIfN1y8.webp",
  "[吐血]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NTY3OTExdGhpcmRfcGFydHlfczEyOTY2NzU4NzgucG5nEIfN1y8.webp",
  "[再见]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5NzQyNjI2dGhpcmRfcGFydHlfczEyOTY2ODg3MDUucG5nEIfN1y8.webp",
  "[一起嗨皮]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3ODE1NjE0dGhpcmRfcGFydHlfczEyOTY4MzgxNDYucG5nEIfN1y8.webp",
  "[皱眉]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3MDA1ODU1dGhpcmRfcGFydHlfczEyOTY2NzI5NDIucG5nEIfN1y8.webp",
  "[石化]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3MjIxNzc2dGhpcmRfcGFydHlfczEyOTY2NzQwMTMucG5nEIfN1y8.webp",
  "[礼花]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2MDYwNTU0dGhpcmRfcGFydHlfczEyOTY2Njg3MTEucG5nEIfN1y8.webp",
  "[抓狂]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5NTA3Mjg5dGhpcmRfcGFydHlfczEyOTY2ODczMDMucG5nEIfN1y8.webp",
  "[道歉]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3NDU3ODE4dGhpcmRfcGFydHlfczIzMDMzODQyNDcucG5nEIfN1y8.webp",
  "[度假]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA4MDg0NTk5dGhpcmRfcGFydHlfczIzMDMzODYyNjYucG5nEIfN1y8.webp",
  "[跪下]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyODY3ODk5dGhpcmRfcGFydHlfczEyOTY2NTU2NjcucG5nEIfN1y8.webp",
  "[爆炸]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMzQyNzEwdGhpcmRfcGFydHlfczEyOTY2NTcyNjEucG5nEIfN1y8.webp",
  "[花开富贵]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3NjIwNTQ2dGhpcmRfcGFydHlfczIxOTY1ODgzNzgucG5nEIfN1y8.webp",
  "[灯笼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNTgzMDAwdGhpcmRfcGFydHlfczEyOTY2NTQ3MzMucG5nEIfN1y8.webp",
  "[敬礼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MjU2MDA5dGhpcmRfcGFydHlfczEyOTY4NDc2ODkucG5nEIfN1y8.webp",
  "[你好]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3ODA3OTMxdGhpcmRfcGFydHlfczIzMDMzODUxMzAucG5nEIfN1y8.webp",
  "[老司机]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcyMDQ4ODQ0dGhpcmRfcGFydHlfczEyOTY3MDMyMTYucG5nEIfN1y8.webp",
  "[哈欠]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMTMxMDU1dGhpcmRfcGFydHlfczEyOTY2OTY5NzcucG5nEIfN1y8.webp",
  "[好运来]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3Mjc5MTg2dGhpcmRfcGFydHlfczEyOTY4MzQ3NjEucG5nEIfN1y8.webp",
  "[熬夜工作]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3NzYxNzg5dGhpcmRfcGFydHlfczEyOTY4Mzc3OTUucG5nEIfN1y8.webp",
  "[拜托]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3ODM4NTM1dGhpcmRfcGFydHlfczEyOTY2NzczNjAucG5nEIfN1y8.webp",
  "[叉号]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgyOTkxNzY2dGhpcmRfcGFydHlfczEyOTY4MDcxNDUucG5nEIfN1y8.webp",
  "[放假啦]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4NDU1NjQxdGhpcmRfcGFydHlfczIwNDA2NTU0NTYucG5nEIfN1y8.webp",
  "[肌肉]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNzUxNDcydGhpcmRfcGFydHlfczEyOTY2NTEwOTgucG5nEIfN1y8.webp",
  "[猪鼻子]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwODg0Mjk3dGhpcmRfcGFydHlfczEyOTY2NDgxODgucG5nEIfN1y8.webp",
  "[祈福]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3Njk1NTA5dGhpcmRfcGFydHlfczIzMDMzODQ3MDYucG5nEIfN1y8.webp",
  "[疲惫]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg4OTA0NzM2dGhpcmRfcGFydHlfczEyOTY4NDUxNzUucG5nEIfN1y8.webp",
  "[擦鼻涕]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3OTQwOTI4dGhpcmRfcGFydHlfczEyOTY2Nzc4NDEucG5nEIfN1y8.webp",
  "[我爱你]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxODY0OTc4dGhpcmRfcGFydHlfczEyOTY2NTE1NDYucG5nEIfN1y8.webp",
  "[花谢了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMDk0NTY4dGhpcmRfcGFydHlfczEyOTY2NTYzOTgucG5nEIfN1y8.webp",
  "[大鼻孔]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3Mzg4OTkxdGhpcmRfcGFydHlfczEyOTY2NzQ5NDcucG5nEIfN1y8.webp",
  "[难受]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3OTAxOTUydGhpcmRfcGFydHlfczEyOTY4Mzg2MDcucG5nEIfN1y8.webp",
  "[红包]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNjMwODc2dGhpcmRfcGFydHlfczEyOTY2NTQ5NTgucG5nEIfN1y8.webp",
  "[酸了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNjI1MTcxdGhpcmRfcGFydHlfczEyOTY2NTA2NzIucG5nEIfN1y8.webp",
  "[拽妹儿]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQwOTg3NTYxMTIzdGhpcmRfcGFydHlfczIxOTY1ODc5OTQucG5nEIfN1y8.webp",
  "[忙疯了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE4Njg5MTUwdGhpcmRfcGFydHlfczIwNDA2NTgzOTMucG5nEIfN1y8.webp",
  "[放轻松]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg1MTAzNzQwdGhpcmRfcGFydHlfczEyOTY4MjA4NjUucG5nEIfN1y8.webp",
  "[蛋糕]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNDA1NzYzdGhpcmRfcGFydHlfczEyOTY2NDcyNTAucG5nEIfN1y8.webp",
  "[嘘]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5NDQyNDA3dGhpcmRfcGFydHlfczEyOTY2ODY4MjkucG5nEIfN1y8.webp",
  "[赢麻了]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MzM3MTc2dGhpcmRfcGFydHlfczEyOTY4NDgyMDYucG5nEIfN1y8.webp",
  "[骂你]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMDc5NzI4dGhpcmRfcGFydHlfczEyOTY2OTY0NDYucG5nEIfN1y8.webp",
  "[香草蛋糕]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzODc5NDM4dGhpcmRfcGFydHlfczEyOTY4MTMyNzcucG5nEIfN1y8.webp",
  "[老铁]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2MDA0NTQ4dGhpcmRfcGFydHlfczEyOTY2Njg1NDIucG5nEIfN1y8.webp",
  "[嘣]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3MzMxNDExdGhpcmRfcGFydHlfczEyOTY2NzQ2MTYucG5nEIfN1y8.webp",
  "[困]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NTUwNDY3dGhpcmRfcGFydHlfczEyOTY2ODEyNTkucG5nEIfN1y8.webp",
  "[涂指甲]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNjgyNzU5dGhpcmRfcGFydHlfczEyOTY2NTA4NzYucG5nEIfN1y8.webp",
  "[打电话]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3NzE3NzU2dGhpcmRfcGFydHlfczEyOTY4Mzc2MjEucG5nEIfN1y8.webp",
  "[绝]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQxMTY0MTQyMjQxdGhpcmRfcGFydHlfczIxOTg3NDQzMTUucG5nEIfN1y8.webp",
  "[马上安排]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MTc3ODY3dGhpcmRfcGFydHlfczEyOTY4NDcwODcucG5nEIfN1y8.webp",
  "[酷]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxNjAzMTM5dGhpcmRfcGFydHlfczEyOTY3MDAyNjMucG5nEIfN1y8.webp",
  "[右哼哼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NDQ4NDkzdGhpcmRfcGFydHlfczEyOTY2ODA2ODgucG5nEIfN1y8.webp",
  "[狗]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMzcxMDk0dGhpcmRfcGFydHlfczEyOTY2NDk3MjYucG5nEIfN1y8.webp",
  "[已阅]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzIyOTE0MTc1MzQzdGhpcmRfcGFydHlfczE3NDc5NzYxMTUucG5nEIfN1y8.webp",
  "[双鸡]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY1OTQzNDMwdGhpcmRfcGFydHlfczEyOTY2NjgzMzcucG5nEIfN1y8.webp",
  "[学习]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg3NjczOTE4dGhpcmRfcGFydHlfczEyOTY4MzczNzIucG5nEIfN1y8.webp",
  "[暴汗]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NzI4ODYxdGhpcmRfcGFydHlfczEyOTY2NzY3MjkucG5nEIfN1y8.webp",
  "[晚上好]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3ODkyMDMxdGhpcmRfcGFydHlfczIzMDMzODU0MjIucG5nEIfN1y8.webp",
  "[元宝]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMzcwNTQxdGhpcmRfcGFydHlfczEyOTY2NTM1NTkucG5nEIfN1y8.webp",
  "[闭嘴]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwNzA5NDUxdGhpcmRfcGFydHlfczEyOTY2OTQxMjgucG5nEIfN1y8.webp",
  "[跳舞]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNTgyODg4dGhpcmRfcGFydHlfczEyOTY2NDc3NTYucG5nEIfN1y8.webp",
  "[打招呼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMTAwMTk1dGhpcmRfcGFydHlfczEyOTY2NTI2NjEucG5nEIfN1y8.webp",
  "[加1]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgyOTMwMzY2dGhpcmRfcGFydHlfczEyOTY4MDY3NDQucG5nEIfN1y8.webp",
  "[我在]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA3NzUyNzU1dGhpcmRfcGFydHlfczIzMDMzODQ4NjIucG5nEIfN1y8.webp",
  "[进度50]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE5ODkxMjc0dGhpcmRfcGFydHlfczIwNDA2NzQzMzUucG5nEIfN1y8.webp",
  "[龙]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNDI3NDA3dGhpcmRfcGFydHlfczEyOTY2NDk5NTQucG5nEIfN1y8.webp",
  "[期待]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2NTM3MzE2dGhpcmRfcGFydHlfczEyOTY2NzA3NzkucG5nEIfN1y8.webp",
  "[皇冠]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY1ODExMTAwdGhpcmRfcGFydHlfczEyOTY2Njc0NzAucG5nEIfN1y8.webp",
  "[卷]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg2ODEzODEzdGhpcmRfcGFydHlfczEyOTY4MzE2NjcucG5nEIfN1y8.webp",
  "[大哥]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY5NTY4MDM5dGhpcmRfcGFydHlfczEyOTY2ODc1NTkucG5nEIfN1y8.webp",
  "[庆祝]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcwOTcyOTY4dGhpcmRfcGFydHlfczEyOTY2OTU2ODYucG5nEIfN1y8.webp",
  "[鼓掌]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMTg0MzYzdGhpcmRfcGFydHlfczEyOTY2OTczNTkucG5nEIfN1y8.webp",
  "[网红]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzU5NzY2NTgzdGhpcmRfcGFydHlfczEyOTY2NDU1NTMucG5nEIfN1y8.webp",
  "[干杯]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyOTc2NTQ5dGhpcmRfcGFydHlfczEyOTY2NTYwNzMucG5nEIfN1y8.webp",
  "[烟花]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNDI1NzA3dGhpcmRfcGFydHlfczEyOTY2NTM4NDUucG5nEIfN1y8.webp",
  "[戴口罩]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzA0MTA3NDMwdGhpcmRfcGFydHlfczEyOTU5ODQzODkucG5nEIfN1y8.webp",
  "[减1]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzIwNjY1NzY2dGhpcmRfcGFydHlfczEyOTY0MDkyNjYucG5nEIfN1y8.webp",
  "[拍一拍]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Njk5MjUyMzI3dGhpcmRfcGFydHlfczEyOTU5NDg4NTkucG5nEIfN1y8.webp",
  "[安排]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMjk0NTUydGhpcmRfcGFydHlfczEyOTY2OTgxODIucG5nEIfN1y8.webp",
  "[气球]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMjY1NTEwdGhpcmRfcGFydHlfczEyOTY2NTMxNzIucG5nEIfN1y8.webp",
  "[打脸]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NjE3MDU2dGhpcmRfcGFydHlfczEyOTY2NzYyMDgucG5nEIfN1y8.webp",
  "[左哼哼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4MzkyNDgydGhpcmRfcGFydHlfczEyOTY2ODAzMzIucG5nEIfN1y8.webp",
  "[狗粮]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyMjExOTU4dGhpcmRfcGFydHlfczEyOTY2NTMwMDYucG5nEIfN1y8.webp",
  "[化妆]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY2ODg5OTA1dGhpcmRfcGFydHlfczEyOTY2NzI1MzQucG5nEIfN1y8.webp",
  "[思考]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg0MDE3MDY4dGhpcmRfcGFydHlfczEyOTY4MTM5NzQucG5nEIfN1y8.webp",
  "[点点关注]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzcxMjM2OTQwdGhpcmRfcGFydHlfczEyOTY2OTc3OTcucG5nEIfN1y8.webp",
  "[发]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNjg5MjY3dGhpcmRfcGFydHlfczEyOTY2NTUxNDIucG5nEIfN1y8.webp",
  "[劳动节]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzQ1ODA4MTU4OTgxdGhpcmRfcGFydHlfczIzMDMzODY0OTYucG5nEIfN1y8.webp",
  "[元旦快乐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3NjIzMzQydGhpcmRfcGFydHlfczIwNDA2NDcxNDIucG5nEIfN1y8.webp",
  "[鞭炮]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNDc0NjE2dGhpcmRfcGFydHlfczEyOTY2NTQwNjQucG5nEIfN1y8.webp",
  "[右拳]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxOTIwMjgzdGhpcmRfcGFydHlfczEyOTY2NTE4ODIucG5nEIfN1y8.webp",
  "[yes]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzMTQ5NjE2dGhpcmRfcGFydHlfczEyOTY4MDgzODUucG5nEIfN1y8.webp",
  "[遥遥领先]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg5MzgyNTc4dGhpcmRfcGFydHlfczEyOTY4NDg0NDcucG5nEIfN1y8.webp",
  "[板砖]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMDM5NzIwdGhpcmRfcGFydHlfczEyOTY2NTYxNjUucG5nEIfN1y8.webp",
  "[点赞]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzAxNzczNzQ1dGhpcmRfcGFydHlfczEyOTU5NjUzODIucG5nEIfN1y8.webp",
  "[稳]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgwNzQyNjQ1dGhpcmRfcGFydHlfczEyOTY3OTQwMjAucG5nEIfN1y8.webp",
  "[充满干劲]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg1MDU2NzQydGhpcmRfcGFydHlfczEyOTY4MjA0MDYucG5nEIfN1y8.webp",
  "[羊驼]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNzExMDM3dGhpcmRfcGFydHlfczEyOTY2NDc5NjUucG5nEIfN1y8.webp",
  "[健身]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzOTY4MjY5dGhpcmRfcGFydHlfczEyOTY4MTM3NjAucG5nEIfN1y8.webp",
  "[听音乐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg2OTg0OTUxdGhpcmRfcGFydHlfczEyOTY4MzI2ODUucG5nEIfN1y8.webp",
  "[加油]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY3NzgwNjExdGhpcmRfcGFydHlfczEyOTY2NzcwNTcucG5nEIfN1y8.webp",
  "[左拳]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxOTc4MDkzdGhpcmRfcGFydHlfczEyOTY2NTIxNDIucG5nEIfN1y8.webp",
  "[收到]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgyODAwMDUzdGhpcmRfcGFydHlfczEyOTY4MDU0NzgucG5nEIfN1y8.webp",
  "[莫吉托]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzODE2ODUydGhpcmRfcGFydHlfczEyOTY4MTI5ODkucG5nEIfN1y8.webp",
  "[口红]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNDcyNDk0dGhpcmRfcGFydHlfczEyOTY2NDc0MDMucG5nEIfN1y8.webp",
  "[水枪]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwMjU0ODczdGhpcmRfcGFydHlfczEyOTY2NDY3ODAucG5nEIfN1y8.webp",
  "[no]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzMDk2MjAzdGhpcmRfcGFydHlfczEyOTY4MDc3NDQucG5nEIfN1y8.webp",
  "[新年快乐]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTE3ODI1MDAxdGhpcmRfcGFydHlfczIwNDA2NDkwODIucG5nEIfN1y8.webp",
  "[老鼠]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMTg5MzMxdGhpcmRfcGFydHlfczEyOTY2NDkxNTYucG5nEIfN1y8.webp",
  "[摄像机]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYzMjQxNTg5dGhpcmRfcGFydHlfczEyOTY2NTY5OTgucG5nEIfN1y8.webp",
  "[空投]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwMTkzOTg2dGhpcmRfcGFydHlfczEyOTY2NDY1NzUucG5nEIfN1y8.webp",
  "[早上好]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzkwMTY3MzQ0dGhpcmRfcGFydHlfczEyOTY4NTM5MjIucG5nEIfN1y8.webp",
  "[猫]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxMjQ1ODI3dGhpcmRfcGFydHlfczEyOTY2NDkzNzMucG5nEIfN1y8.webp",
  "[睡觉]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzY4NDk0MjY4dGhpcmRfcGFydHlfczEyOTY2ODEwMzQucG5nEIfN1y8.webp",
  "[八倍镜]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzU5ODg5Nzg1dGhpcmRfcGFydHlfczEyOTY2NDYwNjUucG5nEIfN1y8.webp",
  "[胡思乱想]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzkwNjU3MjI5dGhpcmRfcGFydHlfczEyOTY4NTg1NDIucG5nEIfN1y8.webp",
  "[狮子]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYxNTAyNzIwdGhpcmRfcGFydHlfczEyOTY2NTAxNDMucG5nEIfN1y8.webp",
  "[必胜]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzU5NTQyMDM0dGhpcmRfcGFydHlfczEyOTY2NDQ5NDEucG5nEIfN1y8.webp",
  "[南]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYyNzYxMjM0dGhpcmRfcGFydHlfczEyOTY2NTUzNjIucG5nEIfN1y8.webp",
  "[get]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzM1MTIwMzM4NDQydGhpcmRfcGFydHlfczIwNDA2ODIxODIucG5nEIfN1y8.webp",
  "[吃饭]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzNzY4MTY5dGhpcmRfcGFydHlfczEyOTY4MTI4MDEucG5nEIfN1y8.webp",
  "[手柄]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwMDkxNDUydGhpcmRfcGFydHlfczEyOTY2NDYzNzQucG5nEIfN1y8.webp",
  "[坑]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzU5OTg1Nzg3dGhpcmRfcGFydHlfczEyOTY2NDYyMTEucG5nEIfN1y8.webp",
  "[麦克风]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzYwNjQ3MjE4dGhpcmRfcGFydHlfczEyOTY2NDc4NTIucG5nEIfN1y8.webp",
  "[湿巾]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzgzNzIxMzk2dGhpcmRfcGFydHlfczEyOTY4MTI1MDQucG5nEIfN1y8.webp",
  "[疯狂工作]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0Nzg0MDYzODEzdGhpcmRfcGFydHlfczEyOTY4MTQyMzQucG5nEIfN1y8.webp",
  "[勤洗手]":
      "https://p4-plat.wsbkwai.com/kimg/bs2/emotion/CigxNzA0NzAzMjU5MjM4dGhpcmRfcGFydHlfczEyOTU5NzcwODQucG5nEIfN1y8.webp",
};
