import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;
import 'package:dio/dio.dart';
import 'package:cookie_jar/cookie_jar.dart';
import 'package:dio_cookie_manager/dio_cookie_manager.dart';
import 'package:simple_live_core/src/common/core_cancellation.dart';
import 'package:simple_live_core/src/common/core_error.dart';
import 'package:simple_live_core/src/common/http_client.dart';
import 'package:simple_live_core/src/common/kuaishou_live_link.dart';
import 'package:simple_live_core/src/danmaku/kuaishou_danmaku.dart';
import 'package:simple_live_core/src/interface/live_danmaku.dart';
import 'package:simple_live_core/src/interface/live_site.dart';
import 'package:simple_live_core/src/model/live_anchor_item.dart';
import 'package:simple_live_core/src/model/live_category.dart';
import 'package:simple_live_core/src/model/live_category_result.dart';
import 'package:simple_live_core/src/model/live_play_quality.dart';
import 'package:simple_live_core/src/model/live_play_url.dart';
import 'package:simple_live_core/src/model/live_room_detail.dart';
import 'package:simple_live_core/src/model/live_room_item.dart';
import 'package:simple_live_core/src/model/live_search_result.dart';

class KuaishouSite extends LiveSite {
  static const int _liveSearchPageSize = 20;
  static const String userAgent =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
  KuaishouSite() {
    id = "kuaishou";
    name = "快手直播";
  }

  /// 可选的自定义 Cookie
  String customCookie = '';

  /// The kwfv1 value generated by the Kuaishou web client.
  String customKww = '';

  String cookie = '';
  Map<String, String> cookieObj = {};

  static const List<String> _imageExtensions = [
    'svgz',
    'pjp',
    'png',
    'ico',
    'avif',
    'tiff',
    'tif',
    'jfif',
    'svg',
    'xbm',
    'pjpeg',
    'webp',
    'jpg',
    'jpeg',
    'bmp',
    'gif',
  ];

  Map<String, dynamic> get _headers => {
        'User-Agent': userAgent,
        'accept':
            'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'connection': 'keep-alive',
        'sec-ch-ua': 'Google Chrome;v=120, Chromium;v=120, Not=A?Brand;v=24',
        'sec-ch-ua-platform': 'Windows',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'same-origin',
        'Sec-Fetch-User': '?1',
      };

  Map<String, dynamic> _searchHeaders(String keyword) => {
        ..._headersWithCookie,
        'accept': 'application/json, text/plain, */*',
        'referer':
            'https://live.kuaishou.com/search?keyword=${Uri.encodeComponent(keyword)}',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
      };

  Map<String, dynamic> get _headersWithCookie {
    final headers = <String, dynamic>{..._headers};
    final cookieValue = _currentCookieHeader();
    if (cookieValue.isNotEmpty) {
      headers['cookie'] = cookieValue;
    }
    return headers;
  }

  static String resolveServerKww(String cookie, String fallback) {
    for (final part in cookie.split(';')) {
      final item = part.trim();
      if (!item.startsWith('kwfv1=')) {
        continue;
      }
      final value = item.substring('kwfv1='.length).trim();
      if (value.isEmpty) {
        continue;
      }
      try {
        return '${Uri.decodeComponent(value)}###ssrc';
      } catch (_) {
        return '$value###ssrc';
      }
    }
    return fallback.trim();
  }

  static String resolveRoomTitle(Map room) {
    final liveStream =
        room["liveStream"] is Map ? room["liveStream"] as Map : const {};
    final gameInfo =
        room["gameInfo"] is Map ? room["gameInfo"] as Map : const {};
    final author = room["author"] is Map ? room["author"] as Map : const {};
    for (final value in [
      room["caption"],
      room["title"],
      liveStream["caption"],
      liveStream["title"],
      gameInfo["name"],
      author["name"],
    ]) {
      final title = value?.toString().trim() ?? '';
      if (title.isNotEmpty) {
        return title;
      }
    }
    return '';
  }

  static LiveStatusState resolveLiveState(Map room) {
    final liveStream = _resolveLiveStream(room);
    final liveStreamId = liveStream["id"]?.toString().trim() ?? '';
    if (liveStreamId.isNotEmpty ||
        _isLiveFlag(room["isLiving"]) ||
        _isLiveFlag(room["living"]) ||
        _isLiveFlag(liveStream["isLiving"]) ||
        _isLiveFlag(liveStream["living"])) {
      return LiveStatusState.live;
    }
    if (_isOfflineFlag(room["isLiving"]) ||
        _isOfflineFlag(room["living"]) ||
        _isOfflineFlag(liveStream["isLiving"]) ||
        _isOfflineFlag(liveStream["living"])) {
      return LiveStatusState.offline;
    }
    return LiveStatusState.unknown;
  }

  static LiveStatusState resolvePlayListState(dynamic playList) {
    if (playList is! List || playList.isEmpty) {
      return LiveStatusState.unknown;
    }
    final states =
        playList.whereType<Map>().map(resolveLiveState).toList(growable: false);
    if (states.any((state) => state == LiveStatusState.live)) {
      return LiveStatusState.live;
    }
    if (states.isNotEmpty &&
        states.every((state) => state == LiveStatusState.offline)) {
      return LiveStatusState.offline;
    }
    return LiveStatusState.unknown;
  }

  static bool resolveLiveStatus(Map room) =>
      resolveLiveState(room) == LiveStatusState.live;

  static Map _resolveLiveStream(Map room) {
    final nested = room["liveStream"];
    if (nested is Map && nested.isNotEmpty) {
      return nested;
    }
    return room;
  }

  static bool _isLiveFlag(dynamic value) {
    return value == true ||
        value == 1 ||
        value?.toString().toLowerCase() == "true";
  }

  static bool _isOfflineFlag(dynamic value) {
    return value == false ||
        value == 0 ||
        value?.toString().toLowerCase() == "false";
  }

  static List<String> extractPlayableUrls(dynamic value) {
    final urls = <String>[];
    final seen = <String>{};

    void collect(dynamic current) {
      if (current is String) {
        final url = current.trim();
        final uri = Uri.tryParse(url);
        final scheme = uri?.scheme.toLowerCase();
        if (url.isNotEmpty &&
            (scheme == 'http' || scheme == 'https' || scheme == 'rtmp') &&
            seen.add(url)) {
          urls.add(url);
        }
        return;
      }
      if (current is Map) {
        for (final child in current.values) {
          collect(child);
        }
        return;
      }
      if (current is Iterable) {
        for (final child in current) {
          collect(child);
        }
      }
    }

    collect(value);
    return urls;
  }

  @override
  LiveDanmaku getDanmaku() => KuaishouDanmaku();

  // ==================== 分类 ====================

  @override
  Future<List<LiveCategory>> getCategores() async {
    List<LiveCategory> categories = [
      LiveCategory(id: "1", name: "热门", children: []),
      LiveCategory(id: "2", name: "网游", children: []),
      LiveCategory(id: "3", name: "单机", children: []),
      LiveCategory(id: "4", name: "手游", children: []),
      LiveCategory(id: "5", name: "棋牌", children: []),
      LiveCategory(id: "6", name: "娱乐", children: []),
      LiveCategory(id: "7", name: "综合", children: []),
      LiveCategory(id: "8", name: "文化", children: []),
    ];

    for (var category in categories) {
      var subs = await _getAllSubCategories(category);
      category.children.addAll(subs);
    }
    return categories;
  }

  Future<List<LiveSubCategory>> _getAllSubCategories(
    LiveCategory category, {
    int page = 1,
    int pageSize = 30,
  }) async {
    List<LiveSubCategory> allSubs = [];
    try {
      while (true) {
        var subs = await _getSubCategories(category, page, pageSize);
        allSubs.addAll(subs);
        if (subs.length < pageSize) break;
        page++;
      }
    } catch (_) {}
    return allSubs;
  }

  Future<List<LiveSubCategory>> _getSubCategories(
    LiveCategory category,
    int page,
    int pageSize,
  ) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/category/data",
      queryParameters: {"type": category.id, "page": page, "size": pageSize},
      header: _headers,
    );

    List<LiveSubCategory> subs = [];
    for (var item in result["data"]["list"] ?? []) {
      subs.add(
        LiveSubCategory(
          id: item["id"].toString(),
          name: item["name"] ?? "",
          parentId: category.id,
          pic: item["poster"],
        ),
      );
    }
    return subs;
  }

  // ==================== 分类直播间列表 ====================

  @override
  Future<LiveCategoryResult> getCategoryRooms(
    LiveSubCategory category, {
    int page = 1,
  }) async {
    var api = category.id.length < 7
        ? "https://live.kuaishou.com/live_api/gameboard/list"
        : "https://live.kuaishou.com/live_api/non-gameboard/list";

    var result = await HttpClient.instance.getJson(
      api,
      queryParameters: {
        "filterType": 0,
        "pageSize": 20,
        "gameId": category.id,
        "page": page,
      },
      header: _headers,
    );

    var items = <LiveRoomItem>[];
    for (var item in result["data"]["list"] ?? []) {
      var cover = item['poster']?.toString() ?? '';
      if (cover.isNotEmpty && !isImageUrl(cover)) {
        cover = '$cover.jpg';
      }
      items.add(
        LiveRoomItem(
          roomId: item["author"]["id"]?.toString() ?? '',
          title: item['caption']?.toString() ?? '',
          cover: cover,
          userName: item["author"]["name"]?.toString() ?? '',
          online: _parseInt(item["watchingCount"]),
        ),
      );
    }

    return LiveCategoryResult(hasMore: items.length >= 20, items: items);
  }

  // ==================== 推荐直播间 ====================

  @override
  Future<LiveCategoryResult> getRecommendRooms({int page = 1}) async {
    var result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/home/list",
      header: _headers,
    );

    var list = result['data']['list'] ?? [];
    var items = <LiveRoomItem>[];

    for (var item in list) {
      for (var sitem in item["gameLiveInfo"] ?? []) {
        for (var titem in sitem["liveInfo"] ?? []) {
          var author = titem["author"];
          var gameInfo = titem["gameInfo"];
          var cover = gameInfo['poster']?.toString() ?? '';
          items.add(
            LiveRoomItem(
              roomId: author["id"]?.toString() ?? '',
              title: resolveRoomTitle(titem),
              cover: cover,
              userName: author["name"]?.toString() ?? '',
              online: _parseInt(titem["watchingCount"]),
            ),
          );
        }
      }
    }
    if (items.any((item) => item.online > 0)) {
      items.sort((a, b) => b.online.compareTo(a.online));
    }

    return LiveCategoryResult(hasMore: false, items: items);
  }

  // ==================== 搜索 ====================

  @override
  Future<LiveSearchRoomResult> searchRooms(
    String keyword, {
    int page = 1,
    CoreCancellation? cancellation,
  }) async {
    Object? primaryError;
    try {
      final result = await _searchLiveStreams(
        keyword,
        page: page,
        cancellation: cancellation,
      );
      return result;
    } on CoreCancelledError {
      rethrow;
    } catch (error) {
      primaryError = error;
    }

    if (page > 1) {
      throw _searchFailure('直播间', primaryError);
    }

    try {
      return await _searchRoomsByOverview(
        keyword,
        cancellation: cancellation,
      );
    } on CoreCancelledError {
      rethrow;
    } catch (fallbackError) {
      throw _searchFallbackFailure('直播间', primaryError, fallbackError);
    }
  }

  Future<LiveSearchRoomResult> _searchLiveStreams(
    String keyword, {
    int page = 1,
    CoreCancellation? cancellation,
  }) async {
    final result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/liveStream",
      queryParameters: {
        "keyword": keyword,
        "page": page,
        "count": _liveSearchPageSize,
        "ussid": "",
      },
      header: _searchHeaders(keyword),
      cancellation: cancellation,
    );

    if (result is! Map) {
      throw _invalidSearchResponse('直播间');
    }
    final data = result["data"];
    if (data is! Map) {
      throw _invalidSearchResponse('直播间');
    }
    if (data["result"] != 1) {
      throw _searchFailure('直播间', data["message"] ?? data["msg"]);
    }

    final list = data["list"];
    if (list is! List) {
      throw _invalidSearchResponse('直播间');
    }
    final items = <LiveRoomItem>[];
    for (final item in list) {
      if (item is! Map) {
        throw _invalidSearchResponse('直播间');
      }
      final room = _parseSearchLiveRoom(item);
      if (room.roomId.isNotEmpty) {
        items.add(room);
      }
    }

    return LiveSearchRoomResult(
      items: items,
      metadata: LiveSearchMetadata(
        continuation: _resolveSearchContinuation(
          data,
          page: page,
          pageSize: _liveSearchPageSize,
        ),
        origin: SearchOrigin.native,
      ),
    );
  }

  Future<LiveSearchRoomResult> _searchRoomsByOverview(
    String keyword, {
    CoreCancellation? cancellation,
  }) async {
    final overview = await _getSearchOverview(
      keyword,
      cancellation: cancellation,
    );
    final liveStreams = _findOverviewSectionList(overview, "liveStreams");
    final items = <LiveRoomItem>[];
    for (final item in liveStreams) {
      if (item is! Map) {
        throw _invalidSearchResponse('概览直播间');
      }
      final room = _parseSearchLiveRoom(item);
      if (room.roomId.isNotEmpty) {
        items.add(room);
      }
    }
    return LiveSearchRoomResult(
      items: items,
      metadata: LiveSearchMetadata(
        continuation: items.isEmpty
            ? SearchContinuation.done
            : SearchContinuation.unknown,
        origin: SearchOrigin.fallback,
      ),
    );
  }

  @override
  Future<LiveSearchAnchorResult> searchAnchors(
    String keyword, {
    int page = 1,
    CoreCancellation? cancellation,
  }) async {
    Object? primaryError;
    try {
      final result = await _searchAnchors(
        keyword,
        page: page,
        cancellation: cancellation,
      );
      return result;
    } on CoreCancelledError {
      rethrow;
    } catch (error) {
      primaryError = error;
    }

    if (page > 1) {
      throw _searchFailure('主播', primaryError);
    }

    try {
      return await _searchAnchorsByOverview(
        keyword,
        cancellation: cancellation,
      );
    } on CoreCancelledError {
      rethrow;
    } catch (fallbackError) {
      throw _searchFallbackFailure('主播', primaryError, fallbackError);
    }
  }

  Future<LiveSearchAnchorResult> _searchAnchors(
    String keyword, {
    int page = 1,
    CoreCancellation? cancellation,
  }) async {
    final result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/author",
      queryParameters: {
        "key": keyword,
        "keyword": keyword,
        "page": page,
        "count": 15,
        "ussid": "",
        "lssid": "",
      },
      header: _searchHeaders(keyword),
      cancellation: cancellation,
    );

    if (result is! Map) {
      throw _invalidSearchResponse('主播');
    }
    final data = result["data"];
    if (data is! Map) {
      throw _invalidSearchResponse('主播');
    }
    if (data["result"] != 1) {
      throw _searchFailure('主播', data["message"] ?? data["msg"]);
    }

    final list = data["list"];
    if (list is! List) {
      throw _invalidSearchResponse('主播');
    }
    final items = <LiveAnchorItem>[];
    for (final item in list) {
      if (item is! Map) {
        throw _invalidSearchResponse('主播');
      }
      final anchor = _parseSearchAnchor(item);
      if (anchor.roomId.isNotEmpty) {
        items.add(anchor);
      }
    }

    return LiveSearchAnchorResult(
      items: items,
      metadata: LiveSearchMetadata(
        continuation: _resolveSearchContinuation(
          data,
          page: page,
          pageSize: 15,
        ),
        origin: SearchOrigin.native,
      ),
    );
  }

  Future<LiveSearchAnchorResult> _searchAnchorsByOverview(
    String keyword, {
    CoreCancellation? cancellation,
  }) async {
    final overview = await _getSearchOverview(
      keyword,
      cancellation: cancellation,
    );
    final authors = _findOverviewSectionList(overview, "authors");
    final items = <LiveAnchorItem>[];
    for (final item in authors) {
      if (item is! Map) {
        throw _invalidSearchResponse('概览主播');
      }
      final anchor = _parseSearchAnchor(item);
      if (anchor.roomId.isNotEmpty) {
        items.add(anchor);
      }
    }
    return LiveSearchAnchorResult(
      items: items,
      metadata: LiveSearchMetadata(
        continuation: items.isEmpty
            ? SearchContinuation.done
            : SearchContinuation.unknown,
        origin: SearchOrigin.fallback,
      ),
    );
  }

  Future<Map> _getSearchOverview(
    String keyword, {
    CoreCancellation? cancellation,
  }) async {
    final result = await HttpClient.instance.getJson(
      "https://live.kuaishou.com/live_api/search/overview",
      queryParameters: {"keyword": keyword, "ussid": ""},
      header: _searchHeaders(keyword),
      cancellation: cancellation,
    );
    if (result is! Map || result["data"] is! Map) {
      throw _invalidSearchResponse('概览');
    }
    return result["data"] as Map;
  }

  SearchContinuation _resolveSearchContinuation(
    Map data, {
    required int page,
    int? pageSize,
  }) {
    for (final key in const <String>[
      'hasMore',
      'hasNext',
      'hasNextPage',
    ]) {
      final value = _parseSearchBoolean(data[key]);
      if (value != null) {
        return value ? SearchContinuation.more : SearchContinuation.done;
      }
    }

    final nextPage = _parseSearchNonNegativeInt(data['nextPage']);
    if (nextPage != null) {
      return nextPage > page
          ? SearchContinuation.more
          : SearchContinuation.done;
    }

    for (final key in const <String>['totalPage', 'pageCount', 'totalPages']) {
      final totalPages = _parseSearchNonNegativeInt(data[key]);
      if (totalPages != null) {
        return page < totalPages
            ? SearchContinuation.more
            : SearchContinuation.done;
      }
    }

    if (pageSize != null) {
      for (final key in const <String>['total', 'totalCount', 'totalSize']) {
        final total = _parseSearchNonNegativeInt(data[key]);
        if (total != null) {
          return page * pageSize < total
              ? SearchContinuation.more
              : SearchContinuation.done;
        }
      }
    }
    return SearchContinuation.unknown;
  }

  bool? _parseSearchBoolean(dynamic value) {
    if (value is bool) return value;
    if (value is num) {
      if (value == 1) return true;
      if (value == 0) return false;
    }
    final normalized = value?.toString().trim().toLowerCase();
    if (normalized == 'true' || normalized == '1') return true;
    if (normalized == 'false' || normalized == '0') return false;
    return null;
  }

  int? _parseSearchNonNegativeInt(dynamic value) {
    final parsed = value is int ? value : int.tryParse(value?.toString() ?? '');
    return parsed != null && parsed >= 0 ? parsed : null;
  }

  CoreError _invalidSearchResponse(String searchType) {
    return CoreError(
      '快手$searchType搜索响应格式错误',
      kind: CoreErrorKind.response,
    );
  }

  CoreError _searchFailure(String searchType, Object? cause) {
    if (cause is CoreError) return cause;
    return CoreError(
      '快手$searchType搜索失败',
      kind: CoreErrorKind.search,
      cause: cause,
    );
  }

  CoreError _searchFallbackFailure(
    String searchType,
    Object primaryError,
    Object fallbackError,
  ) {
    return CoreError(
      '快手$searchType搜索的主接口和概览备用接口均失败',
      kind: CoreErrorKind.search,
      cause: <Object>[primaryError, fallbackError],
    );
  }

  List _findOverviewSectionList(Map overview, String type) {
    final sections = overview["list"];
    if (sections is! List) {
      throw _invalidSearchResponse('概览');
    }
    for (final section in sections) {
      if (section is! Map) {
        throw _invalidSearchResponse('概览');
      }
      if (section["type"] == type) {
        final list = section["list"];
        if (list is! List) {
          throw _invalidSearchResponse('概览');
        }
        return list;
      }
    }
    return const [];
  }

  LiveRoomItem _parseSearchLiveRoom(dynamic item) {
    if (item is! Map) {
      return LiveRoomItem(roomId: '', title: '', cover: '', userName: '');
    }

    var author = item["author"] is Map ? item["author"] as Map : {};
    var gameInfo = item["gameInfo"] is Map ? item["gameInfo"] as Map : {};
    var cover = item["poster"]?.toString() ??
        item["coverUrl"]?.toString() ??
        gameInfo["poster"]?.toString() ??
        '';
    if (cover.isNotEmpty && !isImageUrl(cover)) {
      cover = '$cover.jpg';
    }

    return LiveRoomItem(
      roomId: author["id"]?.toString() ??
          item["authorId"]?.toString() ??
          item["userId"]?.toString() ??
          '',
      title: item["caption"]?.toString() ??
          item["title"]?.toString() ??
          author["name"]?.toString() ??
          '',
      cover: cover,
      userName:
          author["name"]?.toString() ?? item["userName"]?.toString() ?? '',
      online: _parseInt(item["watchingCount"]),
    );
  }

  LiveAnchorItem _parseSearchAnchor(dynamic item) {
    if (item is! Map) {
      return LiveAnchorItem(
        roomId: '',
        avatar: '',
        userName: '',
        liveStatus: false,
      );
    }

    return LiveAnchorItem(
      roomId: item["id"]?.toString() ?? '',
      avatar: item["avatar"]?.toString() ?? '',
      userName: item["name"]?.toString() ?? '',
      liveStatus: item["living"] == true,
    );
  }

  // ==================== 房间详情 ====================

  @override
  Future<LiveRoomDetail> getRoomDetail({required String roomId}) async {
    final url = KuaishouLiveLink.publicRoomUrl(roomId);
    final prefetchedPage = await _getCookie(url);

    LiveRoomDetail? detail;
    if (prefetchedPage != null && prefetchedPage.isNotEmpty) {
      detail = await _parseRoomDetail(prefetchedPage, roomId);
    }
    if (detail == null && _currentCookieHeader().isNotEmpty) {
      detail = await _loadRoomDetail(
        url: url,
        roomId: roomId,
        headers: _headersWithCookie,
      );
    }

    if (detail?.resolvedLiveStatus != LiveStatusState.live) {
      final anonymousDetail = await _loadRoomDetail(
        url: url,
        roomId: roomId,
        headers: _headers,
      );
      detail = _preferRoomDetail(detail, anonymousDetail);
    }

    if (detail == null) {
      throw CoreError("快手直播间详情解析失败，请稍后重试");
    }

    unawaited(
      _registerDid(
        categoryId: detail.categoryId,
        categoryName: detail.categoryName,
      ),
    );
    return detail;
  }

  LiveRoomDetail? _preferRoomDetail(
    LiveRoomDetail? primary,
    LiveRoomDetail? secondary,
  ) {
    if (primary == null) return secondary;
    if (secondary == null) return primary;
    if (primary.resolvedLiveStatus == LiveStatusState.live) return primary;
    if (secondary.resolvedLiveStatus == LiveStatusState.live) return secondary;
    if (primary.resolvedLiveStatus != LiveStatusState.unknown) return primary;
    return secondary;
  }

  Future<LiveRoomDetail?> _loadRoomDetail({
    required String url,
    required String roomId,
    required Map<String, dynamic> headers,
  }) async {
    try {
      final resultText = await HttpClient.instance.getText(
        url,
        queryParameters: const {},
        header: headers,
      );
      return await _parseRoomDetail(resultText, roomId);
    } catch (_) {
      return null;
    }
  }

  Future<LiveRoomDetail?> _parseRoomDetail(
    String resultText,
    String roomId,
  ) async {
    try {
      final text = RegExp(
        r"window\.__INITIAL_STATE__=(.*?);",
        multiLine: false,
      ).firstMatch(resultText)?.group(1);
      if (text == null) {
        return null;
      }

      final transferData = text.replaceAll("undefined", "null");
      final jsonObj = jsonDecode(transferData);
      final liveroom = jsonObj["liveroom"];
      if (liveroom is! Map) {
        return null;
      }
      final playList = liveroom["playList"];
      if (playList is! List || playList.isEmpty) {
        return null;
      }
      final rooms = playList.whereType<Map>().toList(growable: false);
      if (rooms.isEmpty) {
        return null;
      }

      final liveState = resolvePlayListState(playList);
      var selected = rooms.first;
      if (liveState == LiveStatusState.live) {
        selected = rooms.firstWhere(
          (room) => resolveLiveState(room) == LiveStatusState.live,
        );
      }

      final liveStream = _resolveLiveStream(selected);
      final author =
          selected["author"] is Map ? selected["author"] as Map : const {};
      final gameInfo =
          selected["gameInfo"] is Map ? selected["gameInfo"] as Map : const {};
      final resolvedRoomId = author["id"]?.toString() ?? roomId;
      final liveStreamId = liveStream["id"]?.toString().trim() ?? '';
      final playUrls = liveStream["playUrls"] ?? selected["playUrls"];

      var websocketUrls = <String>[];
      void addWebsocketUrls(dynamic values) {
        if (values is! Iterable) return;
        for (final item in values) {
          final websocketUrl = item?.toString().trim() ?? '';
          if (websocketUrl.isNotEmpty &&
              !websocketUrls.contains(websocketUrl)) {
            websocketUrls.add(websocketUrl);
          }
        }
      }

      addWebsocketUrls(liveroom["websocketUrls"]);
      var danmakuToken = liveroom["token"]?.toString().trim() ?? '';
      final embeddedWebsocketInfo = selected["websocketInfo"] is Map
          ? selected["websocketInfo"] as Map
          : const {};
      if (danmakuToken.isEmpty) {
        danmakuToken = embeddedWebsocketInfo["token"]?.toString().trim() ?? '';
      }
      if (websocketUrls.isEmpty) {
        addWebsocketUrls(
          embeddedWebsocketInfo["websocketUrls"] ??
              embeddedWebsocketInfo["webSocketAddresses"],
        );
      }

      var cover = liveStream["poster"]?.toString() ??
          selected["poster"]?.toString() ??
          '';
      if (cover.isNotEmpty && !isImageUrl(cover)) {
        cover = '$cover.jpg';
      }

      late final KuaishouDanmakuArgs danmakuArgs;
      danmakuArgs = KuaishouDanmakuArgs(
        roomId: resolvedRoomId,
        liveStreamId: liveStreamId,
        token: danmakuToken,
        websocketUrls: websocketUrls,
        pageId: _generatePageId(),
        expTag: liveStream["expTag"]?.toString() ?? '',
        attach: selected["expTag"]?.toString() ?? '',
        cookie: _currentCookieHeader(),
        userAgent: userAgent,
        credentialResolver: () => _resolveDanmakuCredentials(danmakuArgs),
      );

      return LiveRoomDetail(
        roomId: resolvedRoomId,
        title: resolveRoomTitle(selected),
        cover: cover,
        userName: author["name"]?.toString() ?? '',
        userAvatar: author["avatar"]?.toString() ?? '',
        online: liveState == LiveStatusState.live
            ? _parseInt(
                selected["watchingCount"] ??
                    liveStream["watchingCount"] ??
                    gameInfo["watchingCount"],
              )
            : 0,
        introduction: author["description"]?.toString(),
        notice: author["description"]?.toString(),
        status: liveState == LiveStatusState.live,
        liveStatusState: liveState,
        url: KuaishouLiveLink.publicRoomUrl(resolvedRoomId),
        data: playUrls,
        danmakuData: danmakuArgs,
        categoryId: gameInfo["id"]?.toString(),
        categoryName: gameInfo["name"]?.toString(),
      );
    } catch (_) {
      return null;
    }
  }

  Future<_KuaishouWebsocketInfo> _getWebsocketInfoWithRetry({
    required String roomId,
    required String liveStreamId,
  }) async {
    var info = await _getWebsocketInfo(
      roomId: roomId,
      liveStreamId: liveStreamId,
    ).timeout(
      const Duration(seconds: 2),
      onTimeout: _KuaishouWebsocketInfo.empty,
    );
    if (info.token.isNotEmpty && info.websocketUrls.isNotEmpty) {
      return info;
    }

    await Future<void>.delayed(const Duration(milliseconds: 500));
    final retry = await _getWebsocketInfo(
      roomId: roomId,
      liveStreamId: liveStreamId,
    ).timeout(
      const Duration(seconds: 2),
      onTimeout: _KuaishouWebsocketInfo.empty,
    );
    return _KuaishouWebsocketInfo(
      token: retry.token.isNotEmpty ? retry.token : info.token,
      websocketUrls: retry.websocketUrls.isNotEmpty
          ? retry.websocketUrls
          : info.websocketUrls,
    );
  }

  Future<KuaishouDanmakuArgs?> _resolveDanmakuCredentials(
    KuaishouDanmakuArgs initial,
  ) async {
    var args = initial;
    if (args.hasConnectionInfo) {
      return args;
    }

    if (args.liveStreamId.isEmpty) {
      final freshDetail = await _loadRoomDetail(
        url: KuaishouLiveLink.publicRoomUrl(args.roomId),
        roomId: args.roomId,
        headers: _headersWithCookie,
      ).timeout(
        const Duration(seconds: 4),
        onTimeout: () => null,
      );
      final freshArgs = freshDetail?.danmakuData;
      if (freshArgs is KuaishouDanmakuArgs) {
        args = freshArgs;
      }
    }
    if (args.hasConnectionInfo) {
      return args;
    }
    if (args.liveStreamId.isEmpty) {
      return null;
    }

    final info = await _getWebsocketInfoWithRetry(
      roomId: args.roomId,
      liveStreamId: args.liveStreamId,
    );
    final resolved = args.copyWith(
      token: args.token.isNotEmpty ? args.token : info.token,
      websocketUrls: args.websocketUrls.isNotEmpty
          ? args.websocketUrls
          : info.websocketUrls,
    );
    return resolved.hasConnectionInfo ? resolved : null;
  }

  @override
  Future<LiveStatusState> getLiveStatusState({required String roomId}) async {
    try {
      final detail = await getRoomDetail(roomId: roomId);
      return detail.resolvedLiveStatus;
    } catch (_) {
      return LiveStatusState.unknown;
    }
  }

  @override
  Future<bool> getLiveStatus({required String roomId}) async {
    return await getLiveStatusState(roomId: roomId) == LiveStatusState.live;
  }

  // ==================== 清晰度 ====================

  @override
  Future<List<LivePlayQuality>> getPlayQualites({
    required LiveRoomDetail detail,
  }) async {
    final qualities = <LivePlayQuality>[];
    final seenUrls = <String>{};

    void collect(
      dynamic value, {
      String inheritedName = '默认',
      int inheritedSort = 0,
    }) {
      if (value is String) {
        for (final url in extractPlayableUrls(value)) {
          if (seenUrls.add(url)) {
            qualities.add(
              LivePlayQuality(
                quality: inheritedName,
                sort: inheritedSort,
                data: <String>[url],
              ),
            );
          }
        }
        return;
      }
      if (value is Iterable) {
        for (final item in value) {
          collect(
            item,
            inheritedName: inheritedName,
            inheritedSort: inheritedSort,
          );
        }
        return;
      }
      if (value is! Map) {
        return;
      }

      final name = value["name"]?.toString().trim().isNotEmpty == true
          ? value["name"].toString()
          : value["shortName"]?.toString().trim().isNotEmpty == true
              ? value["shortName"].toString()
              : inheritedName;
      final level = value["level"];
      final sort = level is num
          ? level.toInt()
          : int.tryParse(level?.toString() ?? '') ?? inheritedSort;
      final directUrls = extractPlayableUrls(value["url"]);
      for (final url in directUrls) {
        if (seenUrls.add(url)) {
          qualities.add(
            LivePlayQuality(
              quality: name,
              sort: sort,
              data: <String>[url],
            ),
          );
        }
      }
      for (final entry in value.entries) {
        if (entry.key == "url") continue;
        collect(entry.value, inheritedName: name, inheritedSort: sort);
      }
    }

    final data = detail.data;
    if (data is Map && data["h264"] != null) {
      collect(data["h264"]);
      if (qualities.isEmpty) {
        collect(data);
      }
    } else {
      collect(data);
    }

    qualities.sort((a, b) => b.sort.compareTo(a.sort));
    return qualities;
  }

  @override
  Future<LivePlayUrl> getPlayUrls({
    required LiveRoomDetail detail,
    required LivePlayQuality quality,
  }) async {
    return LivePlayUrl(urls: extractPlayableUrls(quality.data));
  }

  // ==================== Cookie 管理 ====================

  Future<String?> _getCookie(String url) async {
    try {
      final dio = Dio();
      final cookieJar = CookieJar();
      dio.interceptors.add(CookieManager(cookieJar));
      final response = await dio
          .get<String>(
            url,
            options: Options(
              headers: _headersWithCookie,
              responseType: ResponseType.plain,
            ),
          )
          .timeout(const Duration(seconds: 4));
      List<Cookie> cookies = await cookieJar.loadForRequest(Uri.parse(url));
      final cookieValues = _parseCookieHeader(customCookie);
      for (var i = 0; i < cookies.length; i++) {
        cookieValues[cookies[i].name] = cookies[i].value;
      }
      cookieObj = cookieValues;
      cookie = _formatCookieHeader(cookieValues);
      return response.data;
    } catch (_) {
      cookieObj = _parseCookieHeader(customCookie);
      cookie = _formatCookieHeader(cookieObj);
      return null;
    }
  }

  Future<_KuaishouWebsocketInfo> _getWebsocketInfo({
    required String roomId,
    required String liveStreamId,
  }) async {
    try {
      final kww = resolveServerKww(_currentCookieHeader(), customKww);
      final result = await HttpClient.instance.getJson(
        "https://live.kuaishou.com/live_api/liveroom/websocketinfo",
        queryParameters: {"liveStreamId": liveStreamId},
        header: {
          ..._headersWithCookie,
          if (kww.isNotEmpty) 'Kww': kww,
          'accept': 'application/json, text/plain, */*',
          'referer': 'https://live.kuaishou.com/u/$roomId',
          'Sec-Fetch-Dest': 'empty',
          'Sec-Fetch-Mode': 'cors',
        },
      );
      final data = result["data"];
      if (data is! Map) {
        return _KuaishouWebsocketInfo.empty();
      }
      final urls = <String>[];
      final websocketUrls = data["websocketUrls"] ??
          data["webSocketAddresses"] ??
          const <dynamic>[];
      for (final item in websocketUrls) {
        final url = item?.toString() ?? '';
        if (url.isNotEmpty) {
          urls.add(url);
        }
      }
      return _KuaishouWebsocketInfo(
        token: data["token"]?.toString() ?? '',
        websocketUrls: urls,
      );
    } catch (e) {
      return _KuaishouWebsocketInfo.empty();
    }
  }

  // ==================== DID 注册 ====================

  Future<void> _registerDid({
    String? categoryId,
    String? categoryName,
  }) async {
    var did = cookieObj['did'];
    if (did == null || did.isEmpty) return;
    try {
      await HttpClient.instance.postJson(
        'https://log-sdk.ksapisrv.com/rest/wd/common/log/collect/misc2?v=3.9.49&kpn=KS_GAME_LIVE_PC',
        header: _headers,
        data: _buildMisc2Data(
          did,
          categoryId: categoryId,
          categoryName: categoryName,
        ),
      );
    } catch (_) {}
  }

  Map<String, dynamic> _buildMisc2Data(
    String did, {
    String? categoryId,
    String? categoryName,
  }) {
    return {
      'common': {
        'identity_package': {'device_id': did, 'global_id': ''},
        'app_package': {
          'language': 'zh-CN',
          'platform': 10,
          'container': 'WEB',
          'product_name': 'KS_GAME_LIVE_PC',
        },
        'device_package': {
          'os_version': 'NT 10.0',
          'model': 'Windows',
          'ua':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        },
        'need_encrypt': 'false',
        'network_package': {'type': 3},
        'h5_extra_attr':
            '{"sdk_name":"webLogger","sdk_version":"3.9.49","sdk_bundle":"log.common.js","app_version_name":"","host_product":"","resolution":"1920x1080","screen_with":1920,"screen_height":1080,"device_pixel_ratio":1,"domain":"https://live.kuaishou.com"}',
        'global_attr': '{}',
      },
      'logs': [
        {
          'client_timestamp': DateTime.now().millisecondsSinceEpoch,
          'client_increment_id': math.Random().nextInt(8999) + 1000,
          'session_id': _generateSessionId(),
          'time_zone': 'GMT+08:00',
          'event_package': {
            'task_event': {
              'type': 1,
              'status': 0,
              'operation_type': 1,
              'operation_direction': 0,
              'session_id': _generateSessionId(),
              'url_package': {
                'page': 'GAME_DETAL_PAGE',
                'identity': _generateUuid(),
                'page_type': 2,
                'params': jsonEncode({
                  'game_id': categoryId ?? '',
                  'game_name': categoryName ?? '',
                }),
              },
              'element_package': {},
            },
          },
        },
      ],
    };
  }

  String _generateSessionId() {
    return '${_hex(8)}-${_hex(4)}-${_hex(4)}-${_hex(4)}-${_hex(12)}';
  }

  String _generateUuid() {
    return '${_hex(8)}-${_hex(4)}-${_hex(4)}-${_hex(4)}-${_hex(12)}';
  }

  String _generatePageId() {
    const chars =
        'useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict';
    final random = math.Random();
    return List.generate(16, (_) => chars[random.nextInt(chars.length)]).join();
  }

  String _hex(int length) {
    const chars = '0123456789abcdef';
    var result = '';
    for (var i = 0; i < length; i++) {
      result += chars[math.Random().nextInt(16)];
    }
    return result;
  }

  // ==================== 工具方法 ====================

  static bool isImageUrl(String url) {
    if (url.isEmpty) return false;
    final lastSegment = url.split('?').first.split('/').last;
    // 无扩展名的 http(s) URL（如快手 live3.static.yximgs.com 实时截图
    // "...~1785822457911~1"）是有效的动态图片，直接可用；
    // 若按"无扩展名"处理会拼出 404 的 .jpg，封面失效。
    if (!lastSegment.contains('.')) {
      return true;
    }
    var ext = lastSegment.split('.').last.toLowerCase();
    return _imageExtensions.contains(ext);
  }

  int _parseInt(dynamic value) {
    if (value == null) return 0;
    if (value is int) return value;
    if (value is String) return int.tryParse(value) ?? 0;
    if (value is double) return value.toInt();
    return 0;
  }

  String _currentCookieHeader() {
    return customCookie.isNotEmpty
        ? _mergeCookie(customCookie, cookie)
        : cookie;
  }

  String _mergeCookie(String baseCookie, String extraCookie) {
    final values = _parseCookieHeader(baseCookie);
    values.addAll(_parseCookieHeader(extraCookie));
    return _formatCookieHeader(values);
  }

  Map<String, String> _parseCookieHeader(String cookie) {
    final result = <String, String>{};
    for (final part in cookie.split(';')) {
      final item = part.trim();
      if (item.isEmpty) {
        continue;
      }
      final index = item.indexOf('=');
      if (index <= 0) {
        continue;
      }
      final key = item.substring(0, index).trim();
      final value = item.substring(index + 1).trim();
      if (key.isNotEmpty && value.isNotEmpty) {
        result[key] = value;
      }
    }
    return result;
  }

  String _formatCookieHeader(Map<String, String> values) {
    return values.entries.map((e) => '${e.key}=${e.value}').join('; ');
  }
}

class _KuaishouWebsocketInfo {
  final String token;
  final List<String> websocketUrls;

  _KuaishouWebsocketInfo({required this.token, required this.websocketUrls});

  factory _KuaishouWebsocketInfo.empty() {
    return _KuaishouWebsocketInfo(token: '', websocketUrls: <String>[]);
  }
}
